force-app/main/default/objects/Campaign/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <label>Campaign</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
                <default>true</default>
                <label>German</label>
            </value>
            <value>
                <fullName>en_US</fullName>
                <label>English</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Subscription_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscription Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/History_Tracker__c/History_Tracker__c.object-meta.xml
<CustomObject>
    <label>History Tracker</label>
    <nameField>
        <displayFormat>Track-{00000000}</displayFormat>
        <label>Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Reason_For_Unsubscribing__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Unsubscribing__c</fullName>
    <label>Reason For Unsubscribing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unsubscription_Reasons</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Subscription-{00000}</displayFormat>
        <label>Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Reason_For_Unsubscribing__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Unsubscribing__c</fullName>
    <label>Reason For Unsubscribing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unsubscription_Reasons</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Send_Mail__c.field-meta.xml
<CustomField>
    <fullName>Send_Mail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Mail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Subscription_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscription Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newsletter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <label>Lead</label>
</RecordType>

force-app/main/default/globalValueSets/Product_Subscription_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Subscribed</fullName>
        <default>true</default>
        <label>Not Subscribed</label>
    </customValue>
    <customValue>
        <fullName>Awaiting Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Subscribed</fullName>
    </customValue>
    <customValue>
        <fullName>Unsubscribed</fullName>
    </customValue>
    <customValue>
        <fullName>Resend Confirmation</fullName>
    </customValue>
    <masterLabel>Product Subscription Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Products_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Product C</fullName>
    </customValue>
    <customValue>
        <fullName>Newsletter</fullName>
    </customValue>
    <customValue>
        <fullName>Newletter</fullName>
        <isActive>false</isActive>
        <label>Newletter</label>
    </customValue>
    <masterLabel>Products List</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unsubscription_Reasons.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nicht Offenlegen</fullName>
    </customValue>
    <customValue>
        <fullName>Nicht Interessiert</fullName>
    </customValue>
    <customValue>
        <fullName>Andere</fullName>
    </customValue>
    <masterLabel>Unsubscription Reasons</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SubscriptionService.cls
public without sharing class SubscriptionService {

   	//LWC Component
      /*
     * Description: on load of verification from update terms and condition and subscribe status
     * email:sends product subscribed email
     * //1
	*/ 
    @AuraEnabled
    public static leadWrapper checkAndUpdateSubscriptionOnload(String email, String product) {
        product=product.replace('+',' ');
        leadWrapper respWrapper = new leadWrapper();
        Boolean showForm = true;
         
        
        List<Account> accountDetails=[SELECT id,FirstName,Salutation,LastName,Phone,(Select id,Send_Mail__c,Subscription_Terms_and_Conditions__c,Source__c,Type__c,Subscription_Status__c from Subscriptions__r WHERE Type__c=:product AND RecordTypeId=:Constant.SUBSCRIPTION_DEFAULT_RECORDTYPEID LIMIT 1) 
                                      FROM Account WHERE PersonEmail=:email AND RecordTypeId=:Constant.PERSON_ACCOUNT_RECORDTYPEID];
        if(accountDetails.size()>0){
            Account accountRec = accountDetails.get(0);
            respWrapper.leadId = accountRec.Id;
            if(accountRec.Phone!=null || accountRec.FirstName!=null) showForm = false;
            if(String.isBlank(accountRec.Phone) || String.isBlank(accountRec.FirstName)) showForm = true;
            if(accountRec.Subscriptions__r.size()>0){
                Subscription__c subscription=accountRec.Subscriptions__r.get(0);
                subscription.Subscription_Terms_and_Conditions__c=true;
                subscription.Subscription_Status__c='Subscribed';
                update subscription;
            }
            
        }
        
         
        respWrapper.showForm = showForm;
        return respWrapper;
    }
    
     /*
     * Description: saves lead details when filled in verification form
     * //2
	*/
    @AuraEnabled
    public static Boolean updateSubscriptionWithConfirmation(String email, String product, String salutation, String lastName, String firstName, Boolean termsAndConditions, String phoneNumber, String leadId) {
        Boolean showForm = true;
        
        List<Account> accountDetails=[SELECT id,FirstName,Salutation,LastName,Phone,(Select id,Send_Mail__c,Subscription_Terms_and_Conditions__c,Source__c,Type__c,Subscription_Status__c from Subscriptions__r WHERE Type__c=:product AND RecordTypeId=:Constant.SUBSCRIPTION_DEFAULT_RECORDTYPEID LIMIT 1) 
                                      FROM Account WHERE id=:leadId];
        if(accountDetails.size()>0){
            Account accountRec = accountDetails.get(0);
            if(String.isNotEmpty(salutation?.trim())) accountRec.Salutation = salutation;
            if(String.isNotEmpty(salutation?.trim()) && salutation.contains('Herr')) accountRec.Gender__pc='Male';
            else if(String.isNotEmpty(salutation?.trim()) && salutation.contains('Frau')) accountRec.Gender__pc='Female';
            if(String.isNotEmpty(lastName?.trim())) accountRec.LastName = lastName;
            if(String.isNotEmpty(firstName?.trim()))accountRec.FirstName = firstName;
            if(String.isNotEmpty(phoneNumber?.trim()))accountRec.Phone = phoneNumber;
            if(accountRec.Subscriptions__r.size()>0){
                Subscription__c subscription=accountRec.Subscriptions__r.get(0);
                subscription.Send_Mail__c=true;
                update subscription;
            }
           
            update accountRec;
            showForm=false;
        }
        return showForm;
    }

    
     /*
     * Description: on load of unsubscribe check if its already unsubscribed
     * email:sends successfuly unsubscribed email
     * //3
	*/
    @AuraEnabled
    public static Boolean checkUnsubscribedStatus(String email,String product){
        product=product.replace('+',' ');
        Boolean showForm = true;
        
        List<Account> accountList=[SELECT id,FirstName,Salutation,LastName,Phone,(Select id,Subscription_Terms_and_Conditions__c,Source__c,Type__c,Subscription_Status__c from Subscriptions__r WHERE Type__c=:product AND RecordTypeId=:Constant.SUBSCRIPTION_DEFAULT_RECORDTYPEID LIMIT 1) 
                                      FROM Account WHERE PersonEmail=:email AND RecordTypeId=:Constant.PERSON_ACCOUNT_RECORDTYPEID];
        if(accountList.size()>0){
            Account accountRec = accountList.get(0);
            if(accountRec.Subscriptions__r.size()>0){
                Subscription__c subscription=accountRec.Subscriptions__r.get(0);
                showForm = (subscription.Subscription_Status__c=='Unsubscribed')?false:true;
            }
        }
        
        
        return showForm;
    }
    
   
    /*
     * Description: on load of unsubscribe page product is updateted to unsubscribe
     * email:sends product unsubscribed email
     * //4
	*/
    @AuraEnabled
    public static Boolean updateSubscriptionToUnSubscribed(String email,String product,String reason){
        product=product.replace('+',' ');
        List<String> leadAndContactId=new List<String>();

        List<Account> accountList=[SELECT id,FirstName,Salutation,LastName,Phone,(Select id,Send_Mail__c,Subscription_Terms_and_Conditions__c,Source__c,Type__c,Subscription_Status__c from Subscriptions__r WHERE Type__c=:product AND RecordTypeId=:Constant.SUBSCRIPTION_DEFAULT_RECORDTYPEID LIMIT 1) 
                                   FROM Account WHERE PersonEmail=:email AND RecordTypeId=:Constant.PERSON_ACCOUNT_RECORDTYPEID];
        if(accountList.size()>0){
            Account accountRec = accountList.get(0);
            if(accountRec.Subscriptions__r.size()>0){
                List<Contact> personContact=[SELECT id,Email,Preferred_Language__c FROM Contact WHERE accountId=:accountRec.id AND Account.ispersonaccount=true];
                leadAndContactId.add(personContact.get(0).Id);
                Subscription__c subscription=accountRec.Subscriptions__r.get(0);
                subscription.Subscription_Status__c='Unsubscribed'; 
                subscription.Reason_For_Unsubscribing__c=reason;
                subscription.Send_Mail__c=true;
                update subscription;
            }
        }
        
       
 
        
        List<CampaignMember> campaignMember=[select id from CampaignMember where Campaign.Product__c=:product AND LeadOrContactId IN:leadAndContactId];
        if(campaignMember.size()>0)   delete campaignMember;
        return true;
    }
    
     /*
     * Description: on load of unsubscribe page reasons are loaded
     * //5
	*/
    @AuraEnabled(cacheable=true)
    public static Map<String,String> getUnsubscribeOptions(){
        Map<String,PicklistEntry[]> allPicklistValues=SchemaUtil.getObjectPicklistFileds(SchemaUtil.getSobjectType('Subscription__c'));
        Map<String,String> values=new Map<String,String>();
        for(PicklistEntry entry:allPicklistValues.get('Reason_For_Unsubscribing__c')){
            values.put(entry.getValue(),entry.getLabel());
        }
        return values;
    }
    
     @AuraEnabled
    public static List<History_Tracker__c> getLastEmailSentInfo(String subscriptionId){
        return [SELECT id,User__r.Name,Field__c,New_Value__c,CreatedDate FROM History_Tracker__c WHERE Object__c='Subscription__c' AND  Field__c='Send_Mail__c' AND Record_Id__c=:subscriptionId ORDER BY CreatedDate Desc];
    }
    

    public class leadWrapper{
        @AuraEnabled
        public Boolean showForm;
        @AuraEnabled
        public Id leadId;
    }

}