force-app/main/default/objects/Case/fields/Actual_Result__c.field-meta.xml
<CustomField>
    <fullName>Actual_Result__c</fullName>
    <label>Actual Result</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/App_Version__c.field-meta.xml
<CustomField>
    <fullName>App_Version__c</fullName>
    <label>App Version</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1.9.0</fullName>
            </value>
            <value>
                <fullName>1.8.0</fullName>
                <default>true</default>
                <label>1.8.0</label>
            </value>
            <value>
                <fullName>1.7.0</fullName>
            </value>
            <value>
                <fullName>1.6.0</fullName>
            </value>
            <value>
                <fullName>1.5.6</fullName>
            </value>
            <value>
                <fullName>1.5.5</fullName>
            </value>
            <value>
                <fullName>1.5.4</fullName>
            </value>
            <value>
                <fullName>1.5.3</fullName>
            </value>
            <value>
                <fullName>1.5.2</fullName>
            </value>
            <value>
                <fullName>1.5.1</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>1.4.x</fullName>
            </value>
            <value>
                <fullName>1.2.x</fullName>
            </value>
            <value>
                <fullName>1.1.x</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>0.99</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Internal_Description__c.field-meta.xml
<CustomField>
    <fullName>Internal_Description__c</fullName>
    <label>Internal Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Occurrence_Of_Issue__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Of_Issue__c</fullName>
    <label>Occurrence Of Issue</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phone_Model__c.field-meta.xml
<CustomField>
    <fullName>Phone_Model__c</fullName>
    <label>Phone Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phone_OS__c.field-meta.xml
<CustomField>
    <fullName>Phone_OS__c</fullName>
    <label>Phone OS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>iOS</fullName>
            </value>
            <value>
                <fullName>Android</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DigibankCaseService.cls
public with sharing class DigibankCaseService {

    @AuraEnabled
    public static void prepareBugInfoBody(String caseId){
        List<Case> casesDetails=[SELECT Internal_Description__c ,Id,Subject,Description,Occurrence_Of_Issue__c,Expected_Result__c,Actual_Result__c,
                                 Phone_OS__c,Phone_Model__c,App_Version__c
                                 FROM Case WHERE Id=:caseId];
        System.debug(casesDetails.size());
        if(casesDetails.size()>0){
            String emailBody='';
            Case caseDetails=casesDetails.get(0);
            emailBody += 'Subject';
            emailBody += '\n';
            if(caseDetails.Subject!=null) emailBody += caseDetails.Subject;
            emailBody += '\n';
            emailBody += '\n';
            emailBody += 'Description';
            emailBody += '\n';
            if(caseDetails.Description!=null) emailBody += caseDetails.Description;
            emailBody += '\n';
             
            emailBody += 'Expected Result';
            emailBody += '\n';
            if(caseDetails.Expected_Result__c!=null) emailBody += caseDetails.Expected_Result__c;
            emailBody += '\n';
            emailBody += '\n';
            emailBody += 'Actual Result';
            emailBody += '\n';
            if(caseDetails.Actual_Result__c!=null) emailBody += caseDetails.Actual_Result__c;
            emailBody += '\n';
            emailBody += '\n';
            emailBody += 'Occurrence of issue (time and date)';
            emailBody += '\n';
            if(caseDetails.Occurrence_Of_Issue__c!=null) emailBody += caseDetails.Occurrence_Of_Issue__c?.format();
            emailBody += '\n';
            emailBody += '\n';
            emailBody += 'Phone Model';
            emailBody += '\n';
            if(caseDetails.Phone_Model__c!=null) emailBody += caseDetails.Phone_Model__c;
            emailBody += '\n';
            emailBody += '\n';
            emailBody += 'Phone OS';
            emailBody += '\n';
            if(caseDetails.Phone_OS__c!=null) emailBody += caseDetails.Phone_OS__c;
            emailBody += '\n';
            emailBody += '\n';
            emailBody += 'App Version';
            emailBody += '\n';
            if(caseDetails.App_Version__c!=null) emailBody += caseDetails.App_Version__c;
            emailBody += '\n';
            caseDetails.Internal_Description__c=emailBody;
            update caseDetails;
        }
    }
}