force-app/main/default/objects/Customer_Classification__c/Customer_Classification__c.object-meta.xml
<CustomObject>
    <label>Customer Classification</label>
    <nameField>
        <displayFormat>Classification-{00000}</displayFormat>
        <label>Classification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Classification__c/fields/Internal_Approval__c.field-meta.xml
<CustomField>
    <fullName>Internal_Approval__c</fullName>
    <label>Internal Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Classification__c/fields/System_Status__c.field-meta.xml
<CustomField>
    <fullName>System_Status__c</fullName>
    <label>System Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ONGOING</fullName>
            </value>
            <value>
                <fullName>ONGOING_ADDITIONAL_QUESTIONS</fullName>
            </value>
            <value>
                <fullName>ONGOING_AUTOMATIC_DECLINED</fullName>
            </value>
            <value>
                <fullName>ONGOING_AUTOMATIC_APPROVED</fullName>
            </value>
            <value>
                <fullName>INTERNAL_AUTOMATIC_DECLINED</fullName>
            </value>
            <value>
                <fullName>AWAITING_INTERNAL_PROCESSING</fullName>
            </value>
            <value>
                <fullName>INTERNAL_MANUALLY_APPROVED</fullName>
            </value>
            <value>
                <fullName>INTERNAL_MANUALLY_DECLINED</fullName>
            </value>
            <value>
                <fullName>AWAITING_PARTNER_PROCESSING</fullName>
            </value>
            <value>
                <fullName>PARTNER_MANUALLY_APPROVED</fullName>
            </value>
            <value>
                <fullName>PARTNER_MANUALLY_DECLINED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_Detail__c/KYC_Detail__c.object-meta.xml
<CustomObject>
    <label>KYC Detail</label>
    <nameField>
        <displayFormat>KYC-{00000}</displayFormat>
        <label>KYC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYC Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Update_Website__c.field-meta.xml
<CustomField>
    <fullName>Update_Website__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update Website</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seizure__c/Seizure__c.object-meta.xml
<CustomObject>
    <label>Seizure</label>
    <nameField>
        <displayFormat>Seizure -{00000}</displayFormat>
        <label>Seizure  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seizures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Subscription-{00000}</displayFormat>
        <label>Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Send_Mail__c.field-meta.xml
<CustomField>
    <fullName>Send_Mail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Mail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Subscription_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Subscription_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Subscribed</fullName>
        <default>true</default>
        <label>Not Subscribed</label>
    </customValue>
    <customValue>
        <fullName>Awaiting Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Subscribed</fullName>
    </customValue>
    <customValue>
        <fullName>Unsubscribed</fullName>
    </customValue>
    <customValue>
        <fullName>Resend Confirmation</fullName>
    </customValue>
    <masterLabel>Product Subscription Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FlowCoverageTest.cls
/***************
* @group Test Class
* @description test class for all flows in system
*/
@isTest
public class FlowCoverageTest {

    @isTest
    static void Seizure_Insert_Create_Notification(){
        Account a=TestDataFactory.getPersonAccount(true);
        Seizure__c sei=TestDataFactory.getSeziure(a.Id,True);
    }
    
    @isTest
    static void Subscription_Insert_Update_Send_Email(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Contact c=[SELECT id FROM Contact WHERE accountId=:a.Id];
        Subscription__c sub=TestDataFactory.getNewsletterSubscription(a.Id, c.Id,true);
        sub.Subscription_Status__c='Awaiting Confirmation';
        sub.Send_Mail__c=true;
        update sub;
         
        
    }
    
    @isTest
    static void KYC_Detail_Insert_Send_Notification_to_group(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        KYC_Detail__c kyc=TestDataFactory.getKYCVideoIdentification(a.id,true);
        
    }
    
    @isTest
    static void Opportunity_Update_Send_Stage_Status(){
      
        Test.setMock(HttpCalloutMock.class, new EVExternalServiceTest.EVMockResponse());
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Opportunity o=TestDataFactory.getOpportunityInvestment(a.id,true);
      
        o.StageName='ACTIVE';
        update o;
       
    }
    
    @isTest
    static void Product2_Insert_Send_data_to_external_system(){
        Test.setMock(HttpCalloutMock.class, new Product2ServiceTest.ProductMockResponse());
        
        Product2 prod=TestDataFactory.getInvesetmentProduct('Flow product',false);
        prod.Update_Website__c=true;
        insert prod;
       
    }
    @isTest
    static void Product2_Update_Send_data_to_external_system(){
        Test.setMock(HttpCalloutMock.class, new Product2ServiceTest.ProductMockResponse());
        Product2 prod=TestDataFactory.getInvesetmentProduct('Flow product',true);
       
        prod.Update_Website__c=true;
        update prod;
    
    }
    @isTest
    static void Customer_Classification_Update_Set_System_Status(){
        Test.setMock(HttpCalloutMock.class, new EVExternalServiceTest.EVMockResponse());
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.Id,false);
        cc.System_Status__c='ONGOING';
        insert cc;
        Test.startTest();
        cc.Internal_Approval__c='Customer Rejected';
        update cc;
        Test.stopTest();
        System.debug([SELECT id,System_Status__c From Customer_Classification__c]);
       
    }



}