force-app/main/default/objects/Customer_Classification__c/Customer_Classification__c.object-meta.xml
<CustomObject>
    <label>Customer Classification</label>
    <nameField>
        <displayFormat>Classification-{00000}</displayFormat>
        <label>Classification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Classification__c/fields/Data_Submitted_to_Partner__c.field-meta.xml
<CustomField>
    <fullName>Data_Submitted_to_Partner__c</fullName>
    <label>Data Submitted to Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Classification__c/fields/Internal_Approval__c.field-meta.xml
<CustomField>
    <fullName>Internal_Approval__c</fullName>
    <label>Internal Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Classification__c/fields/Partner_Approval__c.field-meta.xml
<CustomField>
    <fullName>Partner_Approval__c</fullName>
    <label>Partner Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Classification__c/fields/System_Status__c.field-meta.xml
<CustomField>
    <fullName>System_Status__c</fullName>
    <label>System Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ONGOING</fullName>
            </value>
            <value>
                <fullName>ONGOING_ADDITIONAL_QUESTIONS</fullName>
            </value>
            <value>
                <fullName>ONGOING_AUTOMATIC_DECLINED</fullName>
            </value>
            <value>
                <fullName>ONGOING_AUTOMATIC_APPROVED</fullName>
            </value>
            <value>
                <fullName>INTERNAL_AUTOMATIC_DECLINED</fullName>
            </value>
            <value>
                <fullName>AWAITING_INTERNAL_PROCESSING</fullName>
            </value>
            <value>
                <fullName>INTERNAL_MANUALLY_APPROVED</fullName>
            </value>
            <value>
                <fullName>INTERNAL_MANUALLY_DECLINED</fullName>
            </value>
            <value>
                <fullName>AWAITING_PARTNER_PROCESSING</fullName>
            </value>
            <value>
                <fullName>PARTNER_MANUALLY_APPROVED</fullName>
            </value>
            <value>
                <fullName>PARTNER_MANUALLY_DECLINED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerClassificationHandlerTest.cls
/***************
* @group Test Class
* @description test class for CustomerClassificationHandler
*/
@isTest
public class CustomerClassificationHandlerTest {
    
    
    @isTest
    static void processSystemStatusValueValidationRulesInternalApproval1(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Internal_Approval__c='Customer Rejected';
        insert cc;
        Test.startTest();
        try{
            cc.Internal_Approval__c='Pending';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        Test.stopTest();
    }
    @isTest
    static void processSystemStatusValueValidationRulesInternalApproval2(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Internal_Approval__c='Customer Rejected';
        cc.Data_Submitted_to_Partner__c='Yes';
        insert cc;
        Test.startTest();
        try{
            cc.Data_Submitted_to_Partner__c='Pending';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        Test.stopTest();
    }
    @isTest
    static void processSystemStatusValueValidationRulesInternalApproval3(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Internal_Approval__c='Customer Rejected';
        cc.Partner_Approval__c='Pending';
        cc.Data_Submitted_to_Partner__c='No';
        insert cc;
        Test.startTest();
        try{
            cc.Partner_Approval__c='Customer Approved';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        Test.stopTest();
    }
    
    @isTest
    static void processSystemStatusValueValidationRulesPartnerApproval1(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Partner_Approval__c='Customer Rejected';
        insert cc;
        Test.startTest();
        try{
            cc.Partner_Approval__c='Pending';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        Test.stopTest();
    }
    @isTest
    static void processSystemStatusValueValidationRulesPartnerApproval2(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Partner_Approval__c='Customer Rejected';
        insert cc;
        Test.startTest();
        try{
            cc.Data_Submitted_to_Partner__c='No';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        Test.stopTest();
    } 
    @isTest
    static void processSystemStatusValueValidationRulesPartnerApproval3(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Partner_Approval__c='Customer Rejected';
        insert cc;
        Test.startTest();
        try{ 
            cc.Internal_Approval__c='Customer Rejected';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        Test.stopTest();
    }
    
    @isTest
    static void processSystemStatusValueSystemStatusInternalApproval1(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Internal_Approval__c='Pending';
        cc.Data_Submitted_to_Partner__c='Pending';
        cc.Partner_Approval__c='Customer Approved';
        insert cc;
        Test.startTest();
        cc.Partner_Approval__c='Pending';
        update cc;    
        Test.stopTest();
        //System.assert([SELECT id,System_Status__c FROM  Customer_Classification__c WHERE id=:cc.id LIMIT 1].System_Status__c=='AWAITING_INTERNAL_PROCESSING');
    }
    @isTest
    static void processSystemStatusValueSystemStatusInternalApproval2(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Internal_Approval__c='Pending';
        cc.Data_Submitted_to_Partner__c='Pending';
        insert cc;
        Test.startTest();
        try{ 
            cc.Partner_Approval__c='Customer Approved';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        Test.stopTest();
        
    }
    @isTest
    static void processSystemStatusValueSystemStatusInternalApproval3(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Internal_Approval__c='Pending';
        cc.Data_Submitted_to_Partner__c='Pending';
        insert cc;
        Test.startTest();
        try{ 
            cc.Data_Submitted_to_Partner__c='Yes';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        Test.stopTest();
        
    }
    
    @isTest
    static void processSystemStatusValueSystemStatusInternalApproval4(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Internal_Approval__c='Pending';
        insert cc;
        Test.startTest();
        cc.Internal_Approval__c='Customer Rejected';
        update cc;    
        Test.stopTest();
        //System.assert([SELECT id,System_Status__c FROM  Customer_Classification__c WHERE id=:cc.id LIMIT 1].System_Status__c=='INTERNAL_MANUALLY_DECLINED');
    }
    
    
    @isTest
    static void processSystemStatusValueSystemStatusDataSubmittedtoPartner1(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Partner_Approval__c='Pending';
        cc.Data_Submitted_to_Partner__c='Pending';
        insert cc;
        Test.startTest();
        cc.Internal_Approval__c='Customer Approved';
        update cc;    
        Test.stopTest();
        //System.assert([SELECT id,System_Status__c FROM  Customer_Classification__c WHERE id=:cc.id LIMIT 1].System_Status__c=='AWAITING_INTERNAL_PROCESSING');
    }
    @isTest
    static void processSystemStatusValueSystemStatusDataSubmittedtoPartner2(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Partner_Approval__c='Pending';
        cc.Internal_Approval__c='Customer Approved';
        cc.Data_Submitted_to_Partner__c='Pending';
        insert cc;
        Test.startTest();
        try{
            cc.Partner_Approval__c='Customer Approved';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        Test.stopTest();
        
    }
    @isTest
    static void processSystemStatusValueSystemStatusDataSubmittedtoPartner3(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Partner_Approval__c='Pending';
        cc.Internal_Approval__c='Customer Approved';
        
        insert cc;
        Test.startTest();
        cc.Data_Submitted_to_Partner__c='Yes';
        update cc;    
        Test.stopTest();
        //System.assert([SELECT id,System_Status__c FROM  Customer_Classification__c WHERE id=:cc.id LIMIT 1].System_Status__c=='AWAITING_PARTNER_PROCESSING');
    }
    @isTest
    static void processSystemStatusValueSystemStatusDataSubmittedtoPartner4(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        
        cc.Internal_Approval__c='Customer Approved';
        cc.Data_Submitted_to_Partner__c='Yes';
        insert cc;
        Test.startTest();
        cc.Partner_Approval__c='Customer Approved';
        
        update cc;    
        Test.stopTest();
        //System.assert([SELECT id,System_Status__c FROM  Customer_Classification__c WHERE id=:cc.id LIMIT 1].System_Status__c=='PARTNER_MANUALLY_APPROVED');
    }   
    @isTest
    static void processSystemStatusValueSystemStatusDataSubmittedtoPartner5(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        
        cc.Internal_Approval__c='Customer Approved';
        cc.Data_Submitted_to_Partner__c='Yes';
        insert cc;
        Test.startTest();
        cc.Partner_Approval__c='Customer Rejected';
        
        update cc;    
        Test.stopTest();
        //System.assert([SELECT id,System_Status__c FROM  Customer_Classification__c WHERE id=:cc.id LIMIT 1].System_Status__c=='PARTNER_MANUALLY_DECLINED');
    }  
    @isTest
    static void processSystemStatusValueSystemStatusDataSubmittedtoPartner6(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,false);
        cc.Partner_Approval__c='Pending';
        cc.Internal_Approval__c='Customer Approved';
        cc.Data_Submitted_to_Partner__c='Pending';
        insert cc;
        Test.startTest();
        try{
            cc.Data_Submitted_to_Partner__c='No';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        Test.stopTest();
        
    }
    
    @isTest
    static void processSystemStatusValueNullCheck(){
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Customer_Classification__c cc=TestDataFactory.getProfessionalCustomerClassfication(a.id,true);
        try{
            cc.Internal_Approval__c='';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        try{
            cc.Data_Submitted_to_Partner__c='';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
        try{
            cc.Partner_Approval__c='';
            update cc;    
        }
        catch(Exception e){
            //System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        } 
    }
}