force-app/main/default/objects/Asset_Link__c/Asset_Link__c.object-meta.xml
<CustomObject>
    <label>Asset Link</label>
    <nameField>
        <displayFormat>ASL-{00000}</displayFormat>
        <label>Asset Link Numbr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Link__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Links</relationshipLabel>
    <relationshipName>Asset_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AssetService.cls
/***************
* @group Service
* @description all asset related logic are here
*/

public with sharing class AssetService {
    
    /***************
    * @description returns all asset links that are related asset record
    * @param recordId asset record id whose details are needed
    * @return List<Asset_Link__c> returns list of asset links
    * @example
    * AssetService.getAllRealEstateImageLinks(assetId);
    */
    @AuraEnabled
    public static List<Asset_Link__c> getAllRealEstateImageLinks(string recordId){
        return [SELECT Id, Asset__c, Image_Url__c,Name FROM Asset_Link__c WHERE Asset__c=:recordId AND RecordTypeId=:Constant.ASSET_LINK_IMAGE_RECORDTYPEID AND Image_Url__c!=null ];
    }

}