force-app/main/default/objects/Product2/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Sozialimmobilien</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Bank_BIC__c.field-meta.xml
<CustomField>
    <fullName>Bank_BIC__c</fullName>
    <label>Bank BIC</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bank_IBAN__c.field-meta.xml
<CustomField>
    <fullName>Bank_IBAN__c</fullName>
    <label>Bank IBAN</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Current_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Amount invested</inlineHelpText>
    <label>Current Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Duration_in_months__c.field-meta.xml
<CustomField>
    <fullName>Duration_in_months__c</fullName>
    <label>Duration (in months)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fund_Structure__c.field-meta.xml
<CustomField>
    <fullName>Fund_Structure__c</fullName>
    <label>Fund Structure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Investment_Availability_Date__c.field-meta.xml
<CustomField>
    <fullName>Investment_Availability_Date__c</fullName>
    <label>Investment Availability Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Investment_Class__c.field-meta.xml
<CustomField>
    <fullName>Investment_Class__c</fullName>
    <label>Investment Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bridging</fullName>
            </value>
            <value>
                <fullName>geschlossener Spezial-AIF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Minimum_Investment__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Investment__c</fullName>
    <label>Minimum Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Street_Number__c</fullName>
    <label>Street Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <inlineHelpText>Target Amount of product to reach</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <label>Zipcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Product2Service.cls
/***************
* @group Service Class
* @description all product2 object external calls are here
*/
public class Product2Service {
    
    
    
         /***************
     * @description sends new product details to ev
     * @param products list of products
     */
    public static void sendProductDataToExternalSystem(List<Product2> products){
        
        for(Product2 prod:products){
            if(prod.RecordTypeId==Constant.PRODUCT_INVESTMENT_RECORDTYPEID){
                try{
                    LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(prod.Id,'Product2',(Salesforce.isSandbox)?'Mobile':'Production');
                    
                    
                    Map<String,Object> product=new Map<String,Object>();
                    Map<String,Object> location =new Map<String,Object>();
                    Map<String,Object> investment=new Map<String,Object>();
                    Map<String,Object> bankinformation =new Map<String,Object>();
                    
                    product.put('id',prod.id);
                    product.put('status',(prod.IsActive)?'ACTIVE':'INACTIVE');
                    product.put('name',prod.Name);
                    
                    
                    if(prod.City__c!=null)location.put('city',prod.City__c);
                    if(prod.Country__c!=null)location.put('country',prod.Country__c);
                    if(prod.Zipcode__c!=null)location.put('zipcode',prod.Zipcode__c);
                    if(prod.Street__c!=null)location.put('street',prod.Street__c);
                    if(prod.Street_Number__c!=null)location.put('number',prod.Street_Number__c);
                    
                    
                    
                    if(prod.Fund_Structure__c!=null)investment.put('fundStructure',prod.Fund_Structure__c);
                    if(prod.Asset_Class__c!=null)investment.put('assetClass',prod.Asset_Class__c);
                    if(prod.Interest__c!=null)investment.put('interest',prod.Interest__c);
                    if(prod.Property_Type__c!=null)investment.put('propertyType',prod.Property_Type__c);
                    if(prod.Investment_class__c!=null)investment.put('investmentClass',prod.Investment_class__c);
                    if(prod.Duration_in_months__c!=null)investment.put('duration',prod.Duration_in_months__c);
                    if(prod.Current_Amount__c!=null) investment.put('currentAmount',prod.Current_Amount__c);
                    if(prod.Total_Amount__c!=null)investment.put('totalAmount',prod.Total_Amount__c);
                    if(prod.Minimum_Investment__c!=null)investment.put('minimumInvestment',prod.Minimum_Investment__c);
                    if(prod.Investment_Availability_Date__c!=null)investment.put('investmentAvailability',prod.Investment_Availability_Date__c);
                  
                    if(prod.Bank_Name__c!=null)bankinformation.put('bankName',prod.Bank_Name__c);
                    if(prod.Bank_IBAN__c!=null)bankinformation.put('iban',prod.Bank_IBAN__c);
                    if(prod.Bank_BIC__c!=null)bankinformation.put('bic',prod.Bank_BIC__c);
                    
                    if(location.size()>0) product.put('location',location);
                    if(investment.size()>0) product.put('investmentInformation',investment);
                    if(bankinformation.size()>0) product.put('bankingInformation',bankinformation);
                    
                    EVExternalService.sendProductsInfo(JSON.serialize(product), apiCallDetails);
					 
                }
                Catch(Exception e){
                    LogService.LogMetadata errorDetails=new LogService.LogMetadata();
                    errorDetails.addError(e);
                    errorDetails.addMetadataInfo(userinfo.getUserId(), 'Product2ExternalService', 'sendProductDataToExternalSystem', 'Insert - Product2 - Send data to external system','Send Product Data To BE');
                    errorDetails.addRecordInfo('Product2',prod.Id);
                    LogService.logError(errorDetails);
                }
                
            }
            
            
        } 
        
    }
   /***************
     * @description update product details to ev
     * @param products list of products
     */
    public static void  updatedProductDataToExternalSystem(List<Product2> products){
        
        for(Product2 prod:products){
            if(prod.RecordTypeId==Constant.PRODUCT_INVESTMENT_RECORDTYPEID){
                try{
                    LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(prod.Id,'Product2',(Salesforce.isSandbox)?'Mobile':'Production');
                    
                    Map<String,Object> product=new Map<String,Object>();
                    Map<String,Object> location =new Map<String,Object>();
                    Map<String,Object> investment=new Map<String,Object>();
                    Map<String,Object> bankinformation =new Map<String,Object>();
                    
                    product.put('id',prod.id);
                    product.put('status',(prod.IsActive)?'ACTIVE':'INACTIVE');
                    product.put('name',prod.Name);
                    
                    
                    if(prod.City__c!=null)location.put('city',prod.City__c);
                    if(prod.Country__c!=null)location.put('country',prod.Country__c);
                    if(prod.Zipcode__c!=null)location.put('zipcode',prod.Zipcode__c);
                    if(prod.Street__c!=null)location.put('street',prod.Street__c);
                    if(prod.Street_Number__c!=null)location.put('number',prod.Street_Number__c);
                    
                    
                    
                    if(prod.Fund_Structure__c!=null)investment.put('fundStructure',prod.Fund_Structure__c);
                    if(prod.Asset_Class__c!=null)investment.put('assetClass',prod.Asset_Class__c);
                    if(prod.Interest__c!=null)investment.put('interest',prod.Interest__c);
                    if(prod.Property_Type__c!=null)investment.put('propertyType',prod.Property_Type__c);
                    if(prod.Investment_class__c!=null)investment.put('investmentClass',prod.Investment_class__c);
                    if(prod.Duration_in_months__c!=null)investment.put('duration',prod.Duration_in_months__c);
                    if(prod.Current_Amount__c!=null) investment.put('currentAmount',prod.Current_Amount__c);
                    if(prod.Total_Amount__c!=null)investment.put('totalAmount',prod.Total_Amount__c);
                    if(prod.Minimum_Investment__c!=null)investment.put('minimumInvestment',prod.Minimum_Investment__c);
                    if(prod.Investment_Availability_Date__c!=null)investment.put('investmentAvailability',prod.Investment_Availability_Date__c);
                  
                    if(prod.Bank_Name__c!=null)bankinformation.put('bankName',prod.Bank_Name__c);
                    if(prod.Bank_IBAN__c!=null)bankinformation.put('iban',prod.Bank_IBAN__c);
                    if(prod.Bank_BIC__c!=null)bankinformation.put('bic',prod.Bank_BIC__c);
                    
                    if(location.size()>0) product.put('location',location);
                    if(investment.size()>0) product.put('investmentInformation',investment);
                    if(bankinformation.size()>0) product.put('bankingInformation',bankinformation);
                    
                    EVExternalService.updateProductsInfo(JSON.serialize(product),prod.Id, apiCallDetails);
 
                }
                Catch(Exception e){
                    LogService.LogMetadata errorDetails=new LogService.LogMetadata();
                    errorDetails.addError(e);
                    errorDetails.addMetadataInfo(userinfo.getUserId(), 'Product2ExternalService', 'sendProductDataToExternalSystem', 'Insert - Product2 - Send data to external system','Send Product Data To BE');
                    errorDetails.addRecordInfo('Product2',prod.Id);
                    LogService.logError(errorDetails);
                }
                
            }
            
            
        } 
        
    }
    
    
}