force-app/main/default/objects/Product2/fields/Bank_BIC__c.field-meta.xml
<CustomField>
    <fullName>Bank_BIC__c</fullName>
    <label>Bank BIC</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bank_IBAN__c.field-meta.xml
<CustomField>
    <fullName>Bank_IBAN__c</fullName>
    <label>Bank IBAN</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Current_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Amount invested</inlineHelpText>
    <label>Current Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Duration_in_months__c.field-meta.xml
<CustomField>
    <fullName>Duration_in_months__c</fullName>
    <label>Duration (in months)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Expected_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Expected_Distribution__c</fullName>
    <label>Expected Distribution</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Financing_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Financing_Purpose__c</fullName>
    <label>Financing Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Minimum_Investment__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Investment__c</fullName>
    <label>Minimum Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Own_Contribution__c.field-meta.xml
<CustomField>
    <fullName>Own_Contribution__c</fullName>
    <label>Own Contribution</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Repayment__c.field-meta.xml
<CustomField>
    <fullName>Repayment__c</fullName>
    <label>Repayment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Risk_Class__c.field-meta.xml
<CustomField>
    <fullName>Risk_Class__c</fullName>
    <label>Risk Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <inlineHelpText>Target Amount of product to reach</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type_Of_Use__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Use__c</fullName>
    <label>Type Of Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Product2ExternalService.cls
public class Product2ExternalService {
    
    
    
     
    public static void sendProductDataToExternalSystem(List<Product2> products){
        
        for(Product2 prod:products){
            if(prod.RecordTypeId==Constant.PRODUCT_INVESTMENT_RECORDTYPEID){
                try{
                    LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(prod.Id,'Product2',(Salesforce.isSandbox)?'Mobile':'Production');
                    
                    
                    Map<String,Object> product=new Map<String,Object>();
                    Map<String,Object> location =new Map<String,Object>();
                    Map<String,Object> investment=new Map<String,Object>();
                    Map<String,Object> bankinformation =new Map<String,Object>();
                    
                    product.put('id',prod.id);
                    product.put('createdAt',prod.CreatedDate);
                    product.put('status',(prod.IsActive)?'ACTIVE':'INACTIVE');
                    product.put('name',prod.Name);
                    
                    if(prod.Current_Amount__c!=null)product.put('currentAmount',prod.Current_Amount__c);
                    if(prod.Total_Amount__c!=null)product.put('totalAmount',prod.Total_Amount__c);
                    if(prod.Due_Date__c!=null) product.put('dueDate',prod.Due_Date__c);
                    
                    if(prod.City__c!=null)location.put('city',prod.City__c);
                    if(prod.Country__c!=null)location.put('country',prod.Country__c);
                    
                    if(prod.Interest__c!=null)investment.put('interest',prod.Interest__c);
                    if(prod.Expected_Distribution__c!=null)investment.put('expectedDistribution',prod.Expected_Distribution__c);
                   if(prod.Duration_in_months__c!=null)investment.put('duration',prod.Duration_in_months__c);
                    if(prod.Risk_Class__c!=null)investment.put('riskClass',prod.Risk_Class__c);
                    if(prod.Own_Contribution__c!=null)investment.put('ownContribution',prod.Own_Contribution__c);
                    if(prod.Minimum_Investment__c!=null)investment.put('minimumInvestment',prod.Minimum_Investment__c);
                    if(prod.Financing_Purpose__c!=null) investment.put('financingPurpose',prod.Financing_Purpose__c);
                    if(prod.Type_Of_Use__c!=null)investment.put('typeOfUse',prod.Type_Of_Use__c);
                    if(prod.Repayment__c!=null)investment.put('repayment',prod.Repayment__c);
                    
                    if(prod.Bank_Name__c!=null)bankinformation.put('bankName',prod.Bank_Name__c);
                    if(prod.Bank_IBAN__c!=null)bankinformation.put('iban',prod.Bank_IBAN__c);
                    if(prod.Bank_BIC__c!=null)bankinformation.put('bic',prod.Bank_BIC__c);
                    
                    if(location.size()>0) product.put('location',location);
                    if(investment.size()>0) product.put('investmentInformation',investment);
                    if(bankinformation.size()>0) product.put('bankingInformation',bankinformation);
                    
                    EVExternalService.sendProductsInfo(JSON.serialize(product), apiCallDetails);
                }
                Catch(Exception e){
                    LogService.LogMetadata errorDetails=new LogService.LogMetadata();
                    errorDetails.addError(e);
                    errorDetails.addMetadataInfo(userinfo.getUserId(), 'Product2ExternalService', 'sendProductDataToExternalSystem', 'Insert - Product2 - Send data to external system','Send Product Data To BE');
                    errorDetails.addRecordInfo('Product2',prod.Id);
                    LogService.logError(errorDetails);
                }
                
            }
            
            
        } 
        
    }
   
    public static void  updatedProductDataToExternalSystem(List<Product2> products){
        
        for(Product2 prod:products){
            if(prod.RecordTypeId==Constant.PRODUCT_INVESTMENT_RECORDTYPEID){
                try{
                    LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(prod.Id,'Product2',(Salesforce.isSandbox)?'Mobile':'Production');
                    
                    
                    Map<String,Object> product=new Map<String,Object>();
                    Map<String,Object> location =new Map<String,Object>();
                    Map<String,Object> investment=new Map<String,Object>();
                    Map<String,Object> bankinformation =new Map<String,Object>();
                    
                    product.put('id',prod.id);
                    product.put('createdAt',prod.CreatedDate);
                    product.put('status',(prod.IsActive)?'ACTIVE':'INACTIVE');
                    product.put('name',prod.Name);
                    
                    if(prod.Current_Amount__c!=null)product.put('currentAmount',prod.Current_Amount__c);
                    if(prod.Total_Amount__c!=null)product.put('totalAmount',prod.Total_Amount__c);
                    if(prod.Due_Date__c!=null) product.put('dueDate',prod.Due_Date__c);
                    
                    if(prod.City__c!=null)location.put('city',prod.City__c);
                    if(prod.Country__c!=null)location.put('country',prod.Country__c);
                    
                    if(prod.Interest__c!=null)investment.put('interest',prod.Interest__c);
                    if(prod.Expected_Distribution__c!=null)investment.put('expectedDistribution',prod.Expected_Distribution__c);
                    if(prod.Duration_in_months__c!=null)investment.put('duration',prod.Duration_in_months__c);
                    if(prod.Risk_Class__c!=null)investment.put('riskClass',prod.Risk_Class__c);
                    if(prod.Own_Contribution__c!=null)investment.put('ownContribution',prod.Own_Contribution__c);
                    if(prod.Minimum_Investment__c!=null)investment.put('minimumInvestment',prod.Minimum_Investment__c);
                    if(prod.Financing_Purpose__c!=null) investment.put('financingPurpose',prod.Financing_Purpose__c);
                    if(prod.Type_Of_Use__c!=null)investment.put('typeOfUse',prod.Type_Of_Use__c);
                    if(prod.Repayment__c!=null)investment.put('repayment',prod.Repayment__c);
                    
                    if(prod.Bank_Name__c!=null)bankinformation.put('bankName',prod.Bank_Name__c);
                    if(prod.Bank_IBAN__c!=null)bankinformation.put('iban',prod.Bank_IBAN__c);
                    if(prod.Bank_BIC__c!=null)bankinformation.put('bic',prod.Bank_BIC__c);
                    
                    if(location.size()>0) product.put('location',location);
                    if(investment.size()>0) product.put('investmentInformation',investment);
                    if(bankinformation.size()>0) product.put('bankingInformation',bankinformation);
                    
                    EVExternalService.updateProductsInfo(JSON.serialize(product),prod.Id, apiCallDetails);
                }
                Catch(Exception e){
                    LogService.LogMetadata errorDetails=new LogService.LogMetadata();
                    errorDetails.addError(e);
                    errorDetails.addMetadataInfo(userinfo.getUserId(), 'Product2ExternalService', 'sendProductDataToExternalSystem', 'Insert - Product2 - Send data to external system','Send Product Data To BE');
                    errorDetails.addRecordInfo('Product2',prod.Id);
                    LogService.logError(errorDetails);
                }
                
            }
            
            
        } 
        
    }
    
    
}