force-app/main/default/objects/Account/fields/Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Auth0 Identification</description>
    <externalId>true</externalId>
    <inlineHelpText>Auth0 Identification</inlineHelpText>
    <label>Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Last_Viewed_User__c.field-meta.xml
<CustomField>
    <fullName>Last_Viewed_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Viewed User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Read_At__c.field-meta.xml
<CustomField>
    <fullName>Read_At__c</fullName>
    <label>Read At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Requested_At__c.field-meta.xml
<CustomField>
    <fullName>Requested_At__c</fullName>
    <label>Requested At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REQUESTED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>IN_PROGRESS</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Ticket Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DocumentServiceTest.cls
@isTest
public class DocumentServiceTest {
  
    
    @isTest
    static void testFetchDocumentUrl(){
        Test.setMock(HttpCalloutMock.class, new DocumentMockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Document__c doc=TestDataFactory.getDocumentForAccount(a.Id,true);
        Document__c document=[SELECT Read_At__c,Last_Viewed_User__c, Status__c, Requested_At__c, Ticket_Number__c, Id,Account__r.Auth0_Id__c, Account__c,Account__r.Solarisbank_Tenent__c FROM Document__c Limit 1];
        Test.startTest();
        LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(document.Id,'Document__c',document.Account__r.Solarisbank_Tenent__c);
        DocumentService.fetchDocumentUrl(document.Account__r.Auth0_Id__c, document.Ticket_Number__c, apiCallDetails);
        Test.stopTest();
    }
    
    @isTest
    static void requestDocumentUrlTest(){
        Test.setMock(HttpCalloutMock.class, new DocumentMockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Document__c doc=TestDataFactory.getDocumentForAccount(a.Id,true);
        Test.startTest();
        DocumentReadControler.requestDocumentUrl(doc.id);
        Test.stopTest();
        
    }
    @isTest
    static void requestDocumentUrlErrorTest(){
        Test.setMock(HttpCalloutMock.class, new DocumentMockResponse(true));
        Account a=TestDataFactory.getPersonAccount(true);
        Document__c doc=TestDataFactory.getDocumentForAccount(a.Id,true);
        Test.startTest();
        try{
        DocumentReadControler.requestDocumentUrl(doc.id);
        }Catch(Exception e){}
        Test.stopTest();
        
    }
    
      public class DocumentMockResponse implements HttpCalloutMock { 
        Boolean isError{set;get;}
        public DocumentMockResponse(){
            this.isError=false;
        }
        public DocumentMockResponse(Boolean isError){
            this.isError=isError;
        }
        
        public HTTPResponse respond(HTTPRequest req) { 
            String data='{}';
            HttpResponse resp = new HttpResponse(); 
            resp.setStatusCode(200); 
            resp.setStatus('success');  
            if(req.getEndpoint().contains('customers') && req.getEndpoint().contains('documents')){
                data='{"pdfUrlBase64":"https://salesforce-api.dev.ev-smartmoney.com/"}'; 
            } 
            
            if(isError){
                resp.setStatusCode(400); 
                resp.setStatus('error');   
                data='{"error":"failed"}';
            }
            
            resp.setBody(data); 
            return resp; 
            
        }
    }
}