force-app/main/default/objects/Account/fields/Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Auth0 Identification</description>
    <externalId>true</externalId>
    <inlineHelpText>Auth0 Identification</inlineHelpText>
    <label>Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/EVSM_Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>EVSM_Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>EVSM Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Last_Viewed_User__c.field-meta.xml
<CustomField>
    <fullName>Last_Viewed_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Viewed User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Read_At__c.field-meta.xml
<CustomField>
    <fullName>Read_At__c</fullName>
    <label>Read At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Requested_At__c.field-meta.xml
<CustomField>
    <fullName>Requested_At__c</fullName>
    <label>Requested At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REQUESTED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>IN_PROGRESS</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Ticket Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DocumentReadControler.cls
/***************
* @group Controller Class
* @description business logic for aura component documentReadRequest
*/
public with sharing class DocumentReadControler {
    
    
    /***************
    * @description request temprory link from ev to privew fiel for 5 min
    * @param documentId record id of document object
    */
    @AuraEnabled
    public static String requestDocumentUrl(String documentId){
        Try{
           
            Document__c document=[SELECT Opportunity__r.External_id__c,Opportunity__r.Account.Solarisbank_Tenent__c,Opportunity__r.Account.EVSM_Auth0_Id__c,RecordTypeId,Read_At__c,Last_Viewed_User__c, Status__c, Requested_At__c, Ticket_Number__c, Id,Account__r.Auth0_Id__c, Account__c,Account__r.Solarisbank_Tenent__c FROM Document__c WHERE Id=:documentId];
            String accountAuthoId='';
            String tenent='';
            if(document.RecordTypeId==Constant.DOCUMENT_ACCOUNT_RECORDTYPEID) accountAuthoId = document.Account__r.Auth0_Id__c;
            else if(document.RecordTypeId==Constant.DOCUMENT_OPPORTUNTIY_RECORDTYPEID) accountAuthoId = document.Opportunity__r.Account.EVSM_Auth0_Id__c;
            
            if(document.RecordTypeId==Constant.DOCUMENT_ACCOUNT_RECORDTYPEID) tenent = document.Account__r.Solarisbank_Tenent__c;
            else if(document.RecordTypeId==Constant.DOCUMENT_OPPORTUNTIY_RECORDTYPEID) tenent = document.Opportunity__r.Account.Solarisbank_Tenent__c;
            
            
            
           
            
            LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(documentId,'Document__c',tenent);
            
            
            
            String documentResponseBody = '';
            
            if(document.RecordTypeId==Constant.DOCUMENT_ACCOUNT_RECORDTYPEID) documentResponseBody= EVExternalService.fetchDocumentUrl(accountAuthoId, document.Ticket_Number__c, apiCallDetails);    
            else if(document.RecordTypeId==Constant.DOCUMENT_OPPORTUNTIY_RECORDTYPEID) documentResponseBody = EVExternalService.fetchInvestmentDocumentUrl(document.Opportunity__r.External_id__c,accountAuthoId, document.Ticket_Number__c, apiCallDetails); 
            
            
            
            document.Requested_At__c=DateTime.now();
            document.Status__c='REQUESTED';
            document.Read_At__c=DateTime.now();
            document.Last_Viewed_User__c=UserInfo.getUserId();
            
            update document;
            
            return documentResponseBody;
            
            
        }Catch(Exception e){
            
            String index = logError(e,documentId,'Document__c','DocumentReadRequest','requestDocumentUrl','Request Document Url');
            throw new AuraHandledException('Please contact your System admin.And provide '+index+' id to resolve issue.'); 
        }
        
        
    }
    
    //helper
    @testVisible
    private static String logError(Exception e,String recordID,String objectName,String componentName,String methodName,String operation){
        LogService.LogMetadata details=new LogService.LogMetadata();
        details.addError(e);
        details.addRecordInfo(objectName,recordId);
        details.addMetadataInfo(userinfo.getUserId(),'DocumentReadControler', methodName, componentName, operation);
        return LogService.logError(details);
    }
    
}