force-app/main/default/objects/Account/fields/Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Auth0 Identification</description>
    <externalId>true</externalId>
    <inlineHelpText>Auth0 Identification</inlineHelpText>
    <label>Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/EVSM_Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>EVSM_Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>EVSM Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Last_Viewed_User__c.field-meta.xml
<CustomField>
    <fullName>Last_Viewed_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Viewed User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Read_At__c.field-meta.xml
<CustomField>
    <fullName>Read_At__c</fullName>
    <label>Read At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Requested_At__c.field-meta.xml
<CustomField>
    <fullName>Requested_At__c</fullName>
    <label>Requested At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REQUESTED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>IN_PROGRESS</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Ticket Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/EVExternalServiceTest.cls
/***************
* @group Test Class
* @description test class for EVExternalService
*/
@isTest
public class EVExternalServiceTest {
  
    
    @isTest
    static void testFetchDocumentUrl(){ 
        Test.setMock(HttpCalloutMock.class, new EVMockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Document__c doc=TestDataFactory.getDocumentForAccount(a.Id,true);
        Document__c document=[SELECT Read_At__c,Last_Viewed_User__c, Status__c, Requested_At__c, Ticket_Number__c, Id,Account__r.Auth0_Id__c, Account__c,Account__r.Solarisbank_Tenent__c FROM Document__c Limit 1];
        User u=TestDataFactory.getUser('Integration');
        Test.startTest();
        System.runAs(u){
            LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(document.Id,'Document__c',document.Account__r.Solarisbank_Tenent__c);
            EVExternalService.fetchDocumentUrl(document.Account__r.Auth0_Id__c, document.Ticket_Number__c, apiCallDetails);
        }
        Test.stopTest();
    }
    
    @isTest
    static void requestDocumentUrlTest(){
        Test.setMock(HttpCalloutMock.class, new EVMockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Document__c doc=TestDataFactory.getDocumentForAccount(a.Id,true);
        User u=TestDataFactory.getUser('Integration');
        
        Test.startTest();
        System.runAs(u){
            DocumentReadControler.requestDocumentUrl(doc.id);
        }
        Test.stopTest();
        
    }
    
    @isTest
    static void requestInvestmentDocumentUrlTest(){
        Test.setMock(HttpCalloutMock.class, new EVMockResponse());
        Account a=TestDataFactory.getPersonInvestmentAccount(true);
        Opportunity o=TestDataFactory.getOpportunityInvestment(a.id, true);
        
        Document__c doc=TestDataFactory.getDocumentForInvestmentOpportuntiy(o.Id,true);
        User u=TestDataFactory.getUser('Integration');
        
        Test.startTest();
        System.runAs(u){
            try{
            DocumentReadControler.requestDocumentUrl(doc.id);
            }
            Catch(Exception e){
            	System.debug('Error '+e.getMessage());    
            }
        }
        Test.stopTest();
        
    }
    
    @isTest
    static void sendProductsInfoTest(){
        Test.setMock(HttpCalloutMock.class, new Product2ServiceTest.ProductMockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Product2 prod=TestDataFactory.getInvesetmentProduct('TestProd',true); 
        User u=TestDataFactory.getUser('Integration');
        Test.startTest();
        System.runAs(u){
            LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(prod.Id,'Product2','Sandbox');
            EVExternalService.sendProductsInfo('{"id":'+prod.Id+'}', apiCallDetails);
        }
        Test.stopTest();
    }
    
    @isTest
    static void requestDocumentUrlErrorTest(){
        Test.setMock(HttpCalloutMock.class, new EVMockResponse(true));
        Account a=TestDataFactory.getPersonAccount(true);
        Document__c doc=TestDataFactory.getDocumentForAccount(a.Id,true);
        User u=TestDataFactory.getUser('Integration');
        Test.startTest();
        System.runAs(u){
            try{
                DocumentReadControler.requestDocumentUrl(doc.id);
            }Catch(Exception e){}
        }
        Test.stopTest();
        
    }
    

    @isTest
    static void updateProductsInfoTest(){
        Test.setMock(HttpCalloutMock.class, new Product2ServiceTest.ProductMockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Product2 prod=TestDataFactory.getInvesetmentProduct('TestProd',true);
        User u=TestDataFactory.getUser('Integration');
        Test.startTest();
        System.runAs(u){
            LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(prod.Id,'Product2','Mobile');
            EVExternalService.updateProductsInfo('{"id":'+prod.id+'}',prod.Id, apiCallDetails);
        }
        Test.stopTest();
    }
    
    @isTest
    static void sendInvestmentMoneyTransferdStatusTest(){
        Test.setMock(HttpCalloutMock.class, new EVMockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Opportunity opp=TestDataFactory.getOpportunityInvestment(a.Id,true);
        User u=TestDataFactory.getUser('Integration');
        Test.startTest();
        System.runAs(u){
            LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(opp.Id,'Opportunity','Mobile');
            EVExternalService.updateInvestmentUpdate(opp.External_Id__c,a.EVSM_Auth0_Id__c, '{"moneyTransferred":true}', apiCallDetails);
        }
        Test.stopTest();
    }
    @isTest
    static void sendInvestmentDocumentInformationTest(){
        Test.setMock(HttpCalloutMock.class, new EVMockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Opportunity opp=TestDataFactory.getOpportunityInvestment(a.Id,true);
        User u=TestDataFactory.getUser('Integration');
        Test.startTest();
        System.runAs(u){
            LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(opp.Id,'Opportunity','Mobile');
            EVExternalService.sendInvestmentDocumentInformation(opp.Id,'{"status":true}', apiCallDetails);
        }
        Test.stopTest();
    }
    
    @isTest
    static void updateCustomerClassificationUpdateTest(){
        Test.setMock(HttpCalloutMock.class, new EVMockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Opportunity opp=TestDataFactory.getOpportunityInvestment(a.Id,true);
        User u=TestDataFactory.getUser('Integration');
        Test.startTest();
        System.runAs(u){
            LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(opp.Id,'Opportunity','Mobile');
            EVExternalService.updateCustomerClassificationUpdate(opp.Id,a.Id,'{"status":"ONGOING" , "type":"Professional"}', apiCallDetails);
        }
        Test.stopTest();
    }
    
    
    public class EVMockResponse implements HttpCalloutMock { 
        Boolean isError{set;get;}
        public EVMockResponse(){
            this.isError=false;
        }
        public EVMockResponse(Boolean isError){
            this.isError=isError;
        }
        
        public HTTPResponse respond(HTTPRequest req) { 
            String data='{}';
            HttpResponse resp = new HttpResponse(); 
            resp.setStatusCode(200); 
            resp.setStatus('success');  
            if(req.getEndpoint().contains('customers') && req.getEndpoint().contains('documents')){
                data='{"pdfUrlBase64":"https://salesforce-api.dev.ev-smartmoney.com/"}'; 
            } 
            else if(req.getMethod()!='GET'){
                data=req.getBody(); 
            }
            if(isError){
                resp.setStatusCode(400); 
                resp.setStatus('error');   
                data='{"error":"failed"}';
            }
            
            resp.setBody(data); 
            return resp; 
            
        }
    }
}