force-app/main/default/objects/Account/fields/Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Auth0 Identification</description>
    <externalId>true</externalId>
    <inlineHelpText>Auth0 Identification</inlineHelpText>
    <label>Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Banks</relationshipLabel>
    <relationshipName>Banks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Is_Term_Deposit_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Term_Deposit_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Term Deposit Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SolarisbankAdminPanal.cls
public class SolarisbankAdminPanal {

    @AuraEnabled
    public static Boolean getTermDepositeStatus(String recordId){
      
        List<Bank__c> sbList=[SELECT id,Name,Email__c,Solarisbank_Id__c,Is_Term_Deposit_Enabled__c FROM Bank__c WHERE Id=:recordId AND RecordTypeId=:Constant.BANK_SOLARISBANK_RECORDTYPEID];
        return sbList.get(0).Is_Term_Deposit_Enabled__c;
 
     }
    
    //AIM : toggle term deposit tag on auth0 user
    @AuraEnabled
    public static Boolean toggleTermDepostForUser(String recordId,Boolean status,String termDepositReason){
        Boolean changedstatus=false;
        List<Bank__c> sbList=[SELECT id,Name,Email__c,Solarisbank_Id__c,Is_Term_Deposit_Enabled__c,Account__r.Auth0_ID__c,Account__r.Solarisbank_Tenent__c FROM Bank__c WHERE Id=:recordId  AND RecordTypeId=:Constant.BANK_SOLARISBANK_RECORDTYPEID];
      
        
        LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(sbList.get(0).Id,'Bank__c',sbList.get(0).Account__r.Solarisbank_Tenent__c);
        apiCallDetails.requestBody=termDepositReason;
        String responseJson= Auth0Service.updateUserDetails(sbList.get(0).Account__r.Auth0_ID__c,'{ "user_metadata": { "term_deposit_enabled":'+status+' } }',apiCallDetails);
        Auth0Wrapper userDetails=Auth0Wrapper.parse(responseJson);
        
        if(userDetails.user_metadata.term_deposit_enabled==status){
            sbList.get(0).Is_Term_Deposit_Enabled__c=status;
            update sbList;
            changedstatus=true;
        }
        
        return changedstatus;
 
         
    }
}