force-app/main/default/objects/Account/fields/Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Auth0 Identification</description>
    <externalId>true</externalId>
    <inlineHelpText>Auth0 Identification</inlineHelpText>
    <label>Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/EVSM_Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>EVSM_Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>EVSM Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Type_II__c.field-meta.xml
<CustomField>
    <fullName>Type_II__c</fullName>
    <label>Type II</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Issue</fullName>
            </value>
            <value>
                <fullName>Partner Card Block</fullName>
            </value>
            <value>
                <fullName>Card Chargeback</fullName>
            </value>
            <value>
                <fullName>Card Return/Delivery</fullName>
            </value>
            <value>
                <fullName>Fraudulent Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Card Decline</fullName>
            </value>
            <value>
                <fullName>Partner Card Unblock</fullName>
            </value>
            <value>
                <fullName>Partner Card Closure</fullName>
            </value>
            <value>
                <fullName>Closure Request</fullName>
            </value>
            <value>
                <fullName>Account Statement</fullName>
            </value>
            <value>
                <fullName>Closure Info</fullName>
            </value>
            <value>
                <fullName>Account Confirmation</fullName>
            </value>
            <value>
                <fullName>Tax ID Input</fullName>
            </value>
            <value>
                <fullName>Phone Change (Without access)</fullName>
            </value>
            <value>
                <fullName>Identification Creation</fullName>
            </value>
            <value>
                <fullName>Identification Issues</fullName>
            </value>
            <value>
                <fullName>Identification Complaints</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>User Complaint</fullName>
            </value>
            <value>
                <fullName>Payment Request</fullName>
            </value>
            <value>
                <fullName>Direct Debit Return</fullName>
            </value>
            <value>
                <fullName>Incoming Payment investigation</fullName>
            </value>
            <value>
                <fullName>Payment Recall</fullName>
            </value>
            <value>
                <fullName>Seizure Information Request</fullName>
            </value>
            <value>
                <fullName>Seizures Payout</fullName>
            </value>
            <value>
                <fullName>P-Konto</fullName>
            </value>
            <value>
                <fullName>Information Request</fullName>
            </value>
            <value>
                <fullName>Bank Data Deletion</fullName>
            </value>
            <value>
                <fullName>Bank Data Request</fullName>
            </value>
            <value>
                <fullName>Verification Message Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scramble_Configuration__c/Scramble_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration of field and object to scramble PII data</description>
    <label>Scramble Configuration</label>
</CustomObject>

force-app/main/default/classes/AccountArchiveCase.cls
/***************
* @group Queueable Class
* @description Class Responsible for deleting cases of anonimizing data of account and related records based on configuration settings Scramble_Configuration__c
*/
public without sharing class AccountArchiveCase implements Queueable {
    List<String> accountIdList=new List<String>();
    
    public AccountArchiveCase(List<String> accountIds){
        accountIdList=accountIds;
    }
    public void execute(QueueableContext context) {
        try{
        Map<String,List<Case>> accountIdAndCaseListMap=new Map<String,List<Case>>();
        Map<String,String> accountIdAndCaseCsvMap=new Map<String,String>();
        
 		List<Case> allAccountRelatedCases=[SELECT Account.Auth0_ID__c,Account.EVSM_Auth0_Id__c,id,Owner.Name,AccountId,CaseNumber,Type_II__c,RecordType.Name,SuppliedEmail,CreatedDate, SuppliedName, Type, Status, Reason, Origin, Subject, Priority, Description, ContactPhone, ContactMobile, ContactEmail, ContactFax 
                                           FROM Case WHERE AccountId=:accountIdList];  
        
        
        String csvHeader='CaseNumber,RecordType,Status,Origin,Reason,Type,Type 2,Priority,Subject,Description,SuppliedEmail,SuppliedName,Case Owner,CreatedDate';
        for(Case record:allAccountRelatedCases){
            if(accountIdAndCaseListMap.get(record.accountId)==null) accountIdAndCaseListMap.put(record.accountId,new List<Case>());
            accountIdAndCaseListMap.get(record.accountId).add(record);
        }
        
        
        
        for(String accountId:accountIdAndCaseListMap.keySet()){
            String csvFileData=csvHeader+'\n';
            for(Case c:accountIdAndCaseListMap.get(accountId)){
                csvFileData+=c.CaseNumber+',';
                csvFileData+=c.RecordType.Name+',';
                csvFileData+=c.Status+',';
                csvFileData+=c.Origin+',';
                csvFileData+=((c.Reason!=null)?c.Reason:'')+',';
                csvFileData+=((c.Type!=null)?c.Type:'')+','; 
                csvFileData+=((c.Type_II__c!=null)?c.Type_II__c:'')+','; 
                csvFileData+=c.Priority+',';
                csvFileData+=c.Subject+',';
                csvFileData+=((c.Description!=null)?c.Description:'')+',';
                csvFileData+=((c.SuppliedEmail!=null)?c.SuppliedEmail:'')+',';
                csvFileData+=((c.SuppliedName!=null)?c.SuppliedName:'')+',';
                csvFileData+=c.Owner.Name+',';
                csvFileData+=c.CreatedDate+'\n';
                
            }
            accountIdAndCaseCsvMap.put(accountId,csvFileData);
        }
        List<ContentVersion> toInsert = New List<ContentVersion>();
        for(String accountId:accountIdAndCaseCsvMap.keySet()){
            Zippex sampleZip = new Zippex();
            Blob fileData = Blob.valueOf(accountIdAndCaseCsvMap.get(accountid));
            sampleZip.addFile(accountId+'.csv', fileData, null);
            Blob zipData = sampleZip.getZipArchive();
            ContentVersion cv=new ContentVersion();
            cv.FirstPublishLocationId=accountId;
            cv.VersionData=zipData;
            cv.Title=accountId+'.zip';
            cv.PathOnClient=accountId;
            cv.Type__c='Case Archive';
            toInsert.add(cv);
        }
        
         
        if(toInsert.size()>0) logInsertRecordError(Database.insert(toInsert,false));
        
        if(allAccountRelatedCases.size()>0) logDeleteRecordError(Database.delete(allAccountRelatedCases,false));
        }
        catch(Exception e){logError(null,null,'execute',e);}
    }
    
    
    
    @testVisible
    private void logInsertRecordError(List<Database.SaveResult> updateResult){
        for (Database.SaveResult r : updateResult)
        {
            if (!r.isSuccess())    for (Database.Error e : r.getErrors()) logError(r.getId(), e.getMessage()+' : '+e.getFields(),'logInsertRecordError',null);
        }
    }
    
    @testVisible
    private void logDeleteRecordError(List<Database.DeleteResult> updateResult){
        for (Database.DeleteResult r : updateResult)
        {
            if (!r.isSuccess())    for (Database.Error e : r.getErrors()) logError(r.getId(), e.getMessage()+' : '+e.getFields(),'logDeleteRecordError',null);
        }
    }
    
    @testVisible
    private void logError(String errorMessage,String stacktrace,String method,Exception error){
        LogService.LogMetadata metadata=new LogService.LogMetadata();
        metadata.addMetadataInfo(userinfo.getUserId(), 'AccountArchiveCase',method,'Trigger','Delete Account Case');
        metadata.addComment(String.join(accountIdList, ','));
        if(error!=null)metadata.addError(error);
        else metadata.addErrorString(errorMessage,stacktrace);
        LogService.logError(metadata);
        
    }
}