force-app/main/default/objects/Account/fields/Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Auth0 Identification</description>
    <externalId>true</externalId>
    <inlineHelpText>Auth0 Identification</inlineHelpText>
    <label>Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/EVSM_Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>EVSM_Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>EVSM Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/T_C_Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>T_C_Accepted_Date__c</fullName>
    <label>T&amp;C Accepted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/UTM_Campaign__c.field-meta.xml
<CustomField>
    <fullName>UTM_Campaign__c</fullName>
    <label>UTM Campaign</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/UTM_Content__c.field-meta.xml
<CustomField>
    <fullName>UTM_Content__c</fullName>
    <label>UTM Content</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/UTM_Medium__c.field-meta.xml
<CustomField>
    <fullName>UTM_Medium__c</fullName>
    <label>UTM Medium</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/UTM_Source__c.field-meta.xml
<CustomField>
    <fullName>UTM_Source__c</fullName>
    <label>UTM Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/UTM_Term__c.field-meta.xml
<CustomField>
    <fullName>UTM_Term__c</fullName>
    <label>UTM Term</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Subscription_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscription Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KYC_Detail__c/KYC_Detail__c.object-meta.xml
<CustomObject>
    <label>KYC Detail</label>
    <nameField>
        <displayFormat>KYC-{00000}</displayFormat>
        <label>KYC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYC Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KYC_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KYC Details</relationshipLabel>
    <relationshipName>KYC_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KYC_Detail__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>idnow</fullName>
                <label>IDnow</label>
            </value>
            <value>
                <fullName>postident</fullName>
                <label>POSTIDENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_Detail__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KYC_Detail__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KYC_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>successful</fullName>
                <label>Successful</label>
            </value>
            <value>
                <fullName>pending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>expired</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>started</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Subscription-{00000}</displayFormat>
        <label>Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscribed_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscribed_Date__c</fullName>
    <inlineHelpText>Date when user requested for subscription</inlineHelpText>
    <label>Subscribed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Subscription_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscription Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newsletter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/UTM_Campaign__c.field-meta.xml
<CustomField>
    <fullName>UTM_Campaign__c</fullName>
    <label>UTM Campaign</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/UTM_Content__c.field-meta.xml
<CustomField>
    <fullName>UTM_Content__c</fullName>
    <label>UTM Content</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/UTM_Medium__c.field-meta.xml
<CustomField>
    <fullName>UTM_Medium__c</fullName>
    <label>UTM Medium</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/UTM_Source__c.field-meta.xml
<CustomField>
    <fullName>UTM_Source__c</fullName>
    <label>UTM Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/UTM_Term__c.field-meta.xml
<CustomField>
    <fullName>UTM_Term__c</fullName>
    <label>UTM Term</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Subscription_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Subscribed</fullName>
        <default>true</default>
        <label>Not Subscribed</label>
    </customValue>
    <customValue>
        <fullName>Awaiting Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Subscribed</fullName>
    </customValue>
    <customValue>
        <fullName>Unsubscribed</fullName>
    </customValue>
    <customValue>
        <fullName>Resend Confirmation</fullName>
    </customValue>
    <masterLabel>Product Subscription Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RestServiceAccountSMICreate.cls
/***************
* @group Rest Api
* @description Creates Investment Customer 
*/
@RestResource(UrlMapping='/Account/SMI/Create/*')
global without sharing  class RestServiceAccountSMICreate { 

    /***************
    * @description creates/updates customer based on evsm auth0 id or email address
    * @example
      {
       "EVSM_Auth0_ID__c":"",
        "FirstName":"",
        "LastName":"",
        "Gender__pc":"",
        "PersonEmail":"",
        "PersonMobilePhone":"",
        "Invitation_Code__pc":"",
        "Origin__pc":"",
        "Email_Verified__pc":"",
        "T_C_Accepted_Date__c":"",
        "Marketing_Opt_In__pc":"",
        "UTM_Campaign__c":"",
        "UTM_Medium__c":"",
        "UTM_Source__c":"",
        "UTM_Term__c":"",
        "UTM_Content__c":""
      }
    */
	@HttpPatch
    global static void doPatch(){
        final String subscriptionType='Investment-Newsletter';
        List<String> successMessage=new List<String>();
        List<String> errorMessage=new List<String>();
        
        RestResponse res = RestContext.response;
        RestRequest req = RestContext.request;
        Map<String, String> headersMap = req.headers;
        
        String body = req.requestBody.toString();
        if(body==null || String.isBlank(body)){
            res.statusCode = 400;
            res.responseBody=RestResponseWrapper.setError(res.statusCode,new List<String>{'Empty Body'});
            return;
        }
        
        Account newAccount=null;
        Subscription__c subscriptionRecord=null;
        Account newPersonAccount=(Account)  JSON.deserialize(body, Account.class);
        if(newPersonAccount.EVSM_Auth0_ID__c==null || String.isEmpty(newPersonAccount.EVSM_Auth0_ID__c)){
            res.statusCode = 404;
            res.responseBody=RestResponseWrapper.setError(res.statusCode,new List<String>{'EVSM Auth0 Id  not found : '+newPersonAccount.LastName});
            return;
        }
        
        
        //check if account exsits// 
        List<Account> personAccountList=new List<Account>();
        
        personAccountList=[SELECT id,Website,Gender__pc,PersonContactId  ,T_C_Accepted_Date__c ,PersonMobilePhone ,Invitation_Code__pc,Email_Verified__pc,
                                         EVSM_Auth0_ID__c,FirstName,Solarisbank_Id__c,LastName,PersonEmail,Origin__pc,RecordTypeId, 
                                         UTM_Content__c,UTM_Term__c,UTM_Source__c,UTM_Campaign__c,UTM_Medium__c,Auth0_ID__c,
                                         (SELECT id ,Account__c,Contact__c, Subscription_Terms_and_Conditions__c,Subscription_Status__c,Source__c,
                                          UTM_Content__c,UTM_Term__c,UTM_Source__c,UTM_Campaign__c,UTM_Medium__c 
                                          FROM Subscriptions__r WHERE Type__c =:subscriptionType)
                                         FROM Account
                                         WHERE 
                                         EVSM_Auth0_ID__c=:newPersonAccount.EVSM_Auth0_ID__c  
                                         AND 
										 EVSM_Auth0_ID__c!=null                                         
                                         AND 
                                         IsPersonAccount = true
                                         LIMIT 1
                                        ];
        if(personAccountList.size()==0){
            personAccountList=[SELECT id,Website,Gender__pc,PersonContactId  ,T_C_Accepted_Date__c ,PersonMobilePhone ,Invitation_Code__pc,Email_Verified__pc,
                               EVSM_Auth0_ID__c,FirstName,Solarisbank_Id__c,LastName,PersonEmail,Origin__pc,RecordTypeId, 
                               UTM_Content__c,UTM_Term__c,UTM_Source__c,UTM_Campaign__c,UTM_Medium__c,Auth0_ID__c,
                               (SELECT id ,Account__c,Contact__c, Subscription_Terms_and_Conditions__c,Subscription_Status__c,Source__c,
                                UTM_Content__c,UTM_Term__c,UTM_Source__c,UTM_Campaign__c,UTM_Medium__c 
                                FROM Subscriptions__r WHERE Type__c =:subscriptionType)
                               FROM Account
                               WHERE 
                               PersonEmail=:newPersonAccount.PersonEmail  
                               AND 
                               PersonEmail!=null                                         
                               AND 
                               IsPersonAccount = true
                               LIMIT 1
                              ];
        }
       
        
 
        newAccount=(personAccountList.size()>0)?personAccountList.get(0):new Account();
       
        //External Ids
        if(newPersonAccount.EVSM_Auth0_ID__c!=null && newAccount.EVSM_Auth0_ID__c==null)newAccount.EVSM_Auth0_ID__c=newPersonAccount.EVSM_Auth0_ID__c;
        
        //upsert values
        if(newPersonAccount.FirstName!=null)newAccount.FirstName=newPersonAccount.FirstName;
        if(newPersonAccount.LastName!=null)newAccount.LastName=newPersonAccount.LastName;
        if(newPersonAccount.Gender__pc!=null)newAccount.Gender__pc=newPersonAccount.Gender__pc;
        
        if(newPersonAccount.PersonEmail!=null)newAccount.PersonEmail=newPersonAccount.PersonEmail;
        if(newPersonAccount.PersonMobilePhone!=null)newAccount.PersonMobilePhone=newPersonAccount.PersonMobilePhone;
        if(newPersonAccount.Website!=null)newAccount.Website=newPersonAccount.Website;
        
        if(newPersonAccount.Invitation_Code__pc!=null && newAccount.Invitation_Code__pc==null )newAccount.Invitation_Code__pc=newPersonAccount.Invitation_Code__pc;
        
        if(newPersonAccount.Origin__pc!=null){
            if(newAccount.Origin__pc==null) newAccount.Origin__pc=newPersonAccount.Origin__pc;   
            else if(newAccount.Origin__pc!=null && !newAccount.Origin__pc.contains(newPersonAccount.Origin__pc)) newAccount.Origin__pc+=';'+newPersonAccount.Origin__pc; 
        }
        
        //Booleans
        if(newPersonAccount.Email_Verified__pc!=null)newAccount.Email_Verified__pc=newPersonAccount.Email_Verified__pc;
        if(newPersonAccount.T_C_Accepted_Date__c!=null) newAccount.T_C_Accepted_Date__c = newPersonAccount.T_C_Accepted_Date__c;
        if(newPersonAccount.Marketing_Opt_In__pc!=null )newAccount.Marketing_Opt_In__pc=newPersonAccount.Marketing_Opt_In__pc;
        
         //Campaing Values
        if(newPersonAccount.UTM_Campaign__c!=null && newAccount.UTM_Campaign__c==null)newAccount.UTM_Campaign__c=newPersonAccount.UTM_Campaign__c;
        if(newPersonAccount.UTM_Medium__c!=null && newAccount.UTM_Medium__c==null)newAccount.UTM_Medium__c=newPersonAccount.UTM_Medium__c;
        if(newPersonAccount.UTM_Source__c!=null && newAccount.UTM_Source__c==null)newAccount.UTM_Source__c=newPersonAccount.UTM_Source__c;
        if(newPersonAccount.UTM_Term__c!=null && newAccount.UTM_Term__c==null)newAccount.UTM_Term__c=newPersonAccount.UTM_Term__c;
        if(newPersonAccount.UTM_Content__c!=null && newAccount.UTM_Content__c==null) newAccount.UTM_Content__c=newPersonAccount.UTM_Content__c;
        
        //changing record type if user is of both banking and investment
        if(personAccountList.size()==0) newAccount.RecordTypeId=Constant.ACCOUNT_PERSON_INVESTMENT_RECORDTYPEID;
        else if(personAccountList.size()>0 && personAccountList.get(0).Auth0_ID__c!=null && personAccountList.get(0).RecordTypeId!=Constant.ACCOUNT_INVESTMENT_BANKING_RECORDTYPEID) newAccount.RecordTypeId=Constant.ACCOUNT_INVESTMENT_BANKING_RECORDTYPEID; 
       
        
        if(newPersonAccount.Marketing_Opt_In__pc==true){
            subscriptionRecord = new Subscription__c();
            if(personAccountList.size()>0){
                if(personAccountList.get(0).Subscriptions__r.size()>0){
                    subscriptionRecord=personAccountList.get(0).Subscriptions__r.get(0);
                }
            }            
            subscriptionRecord.Type__c=subscriptionType;
            subscriptionRecord.Subscription_Terms_and_Conditions__c=true;
            subscriptionRecord.Subscription_Status__c='Subscribed';
            subscriptionRecord.Source__c=newPersonAccount.Website;
            subscriptionRecord.Subscribed_Date__c=Date.today();
            
            //Campaing Values
            if(newPersonAccount.UTM_Campaign__c!=null && subscriptionRecord.UTM_Campaign__c==null)subscriptionRecord.UTM_Campaign__c=newPersonAccount.UTM_Campaign__c;
            if(newPersonAccount.UTM_Medium__c!=null && subscriptionRecord.UTM_Medium__c==null)subscriptionRecord.UTM_Medium__c=newPersonAccount.UTM_Medium__c;
            if(newPersonAccount.UTM_Source__c!=null && subscriptionRecord.UTM_Source__c==null)subscriptionRecord.UTM_Source__c=newPersonAccount.UTM_Source__c;
            if(newPersonAccount.UTM_Term__c!=null && subscriptionRecord.UTM_Term__c==null)subscriptionRecord.UTM_Term__c=newPersonAccount.UTM_Term__c;
            if(newPersonAccount.UTM_Content__c!=null && subscriptionRecord.UTM_Content__c==null) subscriptionRecord.UTM_Content__c=newPersonAccount.UTM_Content__c;
            
                
        }
        
        
        if(Salesforce.isSandbox && personAccountList.size()==0) newAccount.Solarisbank_Tenent__c='Sandbox';
        
        KYC_Detail__c emptyKycRecord=null;
        List<KYC_Detail__c> kycDetails=[SELECT id FROM KYC_Detail__c WHERE External_Id__c=:newAccount.EVSM_Auth0_ID__c AND Method__c='KYC Flow'];
        if(kycDetails.size()==0){
            emptyKycRecord=new KYC_Detail__c();
            emptyKycRecord.External_Id__c=newAccount.EVSM_Auth0_ID__c;
            emptyKycRecord.State__c = emptyKycRecord.Status__c = 'Pending';
            emptyKycRecord.Method__c='KYC Flow';
        }
        
        
        
        try{
            

            upsert newAccount;
            if(subscriptionRecord!=null){
                //adding contact info to sub record
                if(subscriptionRecord.Account__c==null ) subscriptionRecord.Account__c=newAccount.id;
                if(subscriptionRecord.Contact__c==null ){
                    List<Contact> contactAccountList=[SELECT id FROM Contact WHERE accountId=:newAccount.id AND isPersonAccount=true];
                    if(contactAccountList.size()>0){
                    	subscriptionRecord.Contact__c=contactAccountList.get(0).Id;        
                    }
                }
                
                upsert subscriptionRecord;
            } 
            if(emptyKycRecord!=null){
                emptyKycRecord.Account__c=newAccount.id;
                insert emptyKycRecord;
            }
            successMessage.add(newAccount.id);
            res.statusCode = 201;
            res.responseBody=RestResponseWrapper.setSuccess(res.statusCode,successMessage);
        }
        catch(Exception e){
            System.debug(e.getMessage()+' '+e.getCause());
            errorMessage.add(e.getMessage()+' '+e.getCause());
            errorMessage.add(e.getStackTraceString());
            logError(e,'PATCH',body);
            res.statusCode = 500;
            res.responseBody=RestResponseWrapper.setError(res.statusCode,errorMessage);
        }
        
     } 
    	
    private static void logError(Exception e,String method,String body){
        LogService.LogMetadata elog=new LogService.LogMetadata(); 
        elog.addMetadataInfo(userinfo.getUserId(),'RestServiceAccountSMICreate',method,'',method+' /Account/SMI/Create/*');
        elog.addComment(body);
        elog.addError(e);
        LogService.logError(elog);
    }
}