force-app/main/default/objects/Account/fields/Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Auth0 Identification</description>
    <externalId>true</externalId>
    <inlineHelpText>Auth0 Identification</inlineHelpText>
    <label>Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SINGLE</fullName>
                <label>Single</label>
            </value>
            <value>
                <fullName>MARRIED</fullName>
                <label>Married</label>
            </value>
            <value>
                <fullName>DIVORCED</fullName>
                <label>Divorced</label>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Banks</relationshipLabel>
    <relationshipName>Banks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>SINGLE</fullName>
            </value>
            <value>
                <fullName>MARRIED</fullName>
            </value>
            <value>
                <fullName>DIVORCED</fullName>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account IBAN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <label>Person_Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <formula>TEXT(Person_Account__r.Solarisbank_Tenent__c )</formula>
    <label>Solarisbank Tenent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>NO_BLOCK</fullName>
                <label>No Block</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CHECKING_PERSONAL</fullName>
                <label>Checking Personal</label>
            </value>
            <value>
                <fullName>CHECKING_BUSINESS</fullName>
                <label>Checking Business</label>
            </value>
            <value>
                <fullName>CALL_MONEY</fullName>
                <label>Call Money</label>
            </value>
            <value>
                <fullName>TERM_DEPOSIT</fullName>
                <label>Term Deposit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/Bank_Case_Item__c.object-meta.xml
<CustomObject>
    <label>Bank Case Item</label>
    <nameField>
        <displayFormat>Bank Case Item-{00000}</displayFormat>
        <label>Bank Case Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Case Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Case_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Bank_Case_Item__c/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>Booking-{00000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Change_Request_Log__c/Change_Request_Log__c.object-meta.xml
<CustomObject>
    <label>Change Request Log</label>
    <nameField>
        <displayFormat>CR-{0000000}</displayFormat>
        <label>Change Request Logs Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Request Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_Request_Log__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update Account Details</fullName>
            </value>
            <value>
                <fullName>Term Deposit From</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request_Log__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <label>Solarisbank Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_Request_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUTHORIZATION_REQUIRED</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>CONFIRMATION_REQUIRED</fullName>
            </value>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Change_Request_Log__c/fields/Updated_At__c.field-meta.xml
<CustomField>
    <fullName>Updated_At__c</fullName>
    <label>Updated At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tax_Identification__c/Tax_Identification__c.object-meta.xml
<CustomObject>
    <label>Tax Identification</label>
    <nameField>
        <label>Tax Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Identifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Identification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tax Identifications</relationshipLabel>
    <relationshipName>Tax_Identifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax_Identification__c/fields/Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Identification_Number__c</fullName>
    <label>Identification Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaxExemptionFormController.cls
public without sharing class TaxExemptionFormController {
    
    
    @AuraEnabled(cacheable=true)
    public static String getPersonAccountRecordTypeId(){
        return Constant.PERSON_ACCOUNT_RECORDTYPEID;
    }
    
    
    @AuraEnabled (cacheable=true) 
    public static Map<String,List<sObject>> getCustomerDetails(String sbId,String authId,String sfId){
        if(string.isBlank(sbId)) return new Map<String,List<sObject>>();
        List<Account> accountDetails=[SELECT Id, LastName, Solarisbank_Id__c,
                                      (SELECT id,Name,Marital_Status__c FROM Banks__r WHERE  RecordTypeId=:Constant.BANK_SOLARISBANK_RECORDTYPEID),
                                      (SELECT id,Country__c,Identification_Number__c,Name FROM Tax_Identifications__r WHERE Primary__c=true),
                                      (SELECT Id,Name,CreatedDate FROM Bank_Accounts__r  WHERE Type__c='TERM_DEPOSIT' AND Id=:sfId AND Status__c='NO_BLOCK') 
                                      FROM Account 
                                      WHERE Solarisbank_Id__c=:sbId  AND Auth0_ID__c=:authId];
        List<Booking__c> bookings=[SELECT Id,Booking_Date__c FROM Booking__c where Bank_Account__c=:sfId LIMIT 10];
        return new Map<String,List<sObject>>{
        	'Account'=>accountDetails,
                'Booking'=>bookings
        };
    }
    
    @AuraEnabled
    public static String initiateMFARequest(String sbId,String sfId){
        Account accountDetails=[SELECT id,Solarisbank_Id__c,Solarisbank_Tenent__c FROM Account WHERE id=:sfId];
        LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(accountDetails.Id,'Account',accountDetails.Solarisbank_Tenent__c);
        String response=SolarisbankService.startMFA(sbId, apiCallDetails);
        
        SolarisbankCRPRequestWrapper request=SolarisbankCRPRequestWrapper.parse(response);
        
        insert generateChangeLog(sbId, accountDetails.Id, 'Term Deposit From', 'AUTHORIZATION_REQUIRED', null, '/v1/mfa/challenges/sms', request.created_at);
        
        return response;
    }
    
    @AuraEnabled
    public static SolarisbankCRPRequestWrapper initiateCRPRequest(String sfId,String requestChangebody){
        
        List<Change_Request_Log__c> changeRequestList=new List<Change_Request_Log__c>();
        Account bankAccountDetails=[SELECT Id,Solarisbank_Id__c,Solarisbank_Tenent__c FROM Account WHERE id=:sfId];
        LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(sfId,'Account',bankAccountDetails.Solarisbank_Tenent__c);
        
        String responseString = SolarisbankService.updateCustomerData(bankAccountDetails.Solarisbank_Id__c,requestChangebody,apiCallDetails);
        
        SolarisbankCRPRequestWrapper tanUrlResponse=SolarisbankCRPRequestWrapper.parse(responseString);
        
        if(tanUrlResponse.errors!=null && tanUrlResponse.errors.size()>0){
            changeRequestList.add(generateChangeLog(tanUrlResponse.id, sfId, 'Update Account Details', 'FAILED', tanUrlResponse.errors.get(0).title +' : '+tanUrlResponse.errors.get(0).detail, null, null));
            insert changeRequestList;
            return tanUrlResponse;
        }
        else{
            changeRequestList.add(generateChangeLog(tanUrlResponse.id, sfId, 'Update Account Details', tanUrlResponse.status, null, tanUrlResponse.url, tanUrlResponse.updated_at));
        }
        
        
        String crpResponseString = SolarisbankService.initiateCRPRequest(tanUrlResponse.url,bankAccountDetails.Solarisbank_Id__c,apiCallDetails);
        SolarisbankCRPRequestWrapper crpResponse=SolarisbankCRPRequestWrapper.parse(crpResponseString);
        changeRequestList.add(generateChangeLog(crpResponse.id, sfId, 'Update Account Details', crpResponse.status, null, tanUrlResponse.url.replace('/authorize', '/confirm'), crpResponse.updated_at));
        
        insert changeRequestList;
       
        return tanUrlResponse;  
        
    }
    
    @AuraEnabled
    public static String closeMFARequest(String mfaId,String otp,String sfId){
        Account accountDetails=[SELECT id,Solarisbank_Id__c,Solarisbank_Tenent__c FROM Account WHERE id=:sfId];
        LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(accountDetails.Id,'Account',accountDetails.Solarisbank_Tenent__c);
        String response=SolarisbankService.stopMFA(mfaId,otp, apiCallDetails);
        SolarisbankCRPRequestWrapper request=SolarisbankCRPRequestWrapper.parse(response);
        
        insert generateChangeLog(accountDetails.Solarisbank_Id__c, accountDetails.Id, 'Term Deposit From', (request.status=='success')?'COMPLETED':'FAILED', null, '/v1/mfa/challenges/sms/'+mfaId, request.created_at);
        
        return response;
    }
    
    @AuraEnabled
    public static String closeCRPFRequest(String sfId,String tanurl,String otp,String martialStatus){
        List<Change_Request_Log__c> changeRequestList=new List<Change_Request_Log__c>();
        Account bankAccountDetails=[SELECT Id,Solarisbank_Id__c,Solarisbank_Tenent__c FROM Account WHERE id=:sfId];
        
        List<Bank__c> kycDetails=[SELECT id,Marital_Status__c FROM Bank__c WHERE Account__c=:sfId  AND RecordTypeId=:Constant.BANK_SOLARISBANK_RECORDTYPEID];
        LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(sfId,'Account',bankAccountDetails.Solarisbank_Tenent__c);
        String responseString = SolarisbankService.confirmCRPRequest(tanurl,bankAccountDetails.Solarisbank_Id__c,otp,apiCallDetails);
        SolarisbankCRPRequestWrapper tanUrlResponse=SolarisbankCRPRequestWrapper.parse(responseString);
        
        Change_Request_Log__c crpRequestLog=new Change_Request_Log__c();
        if(tanUrlResponse.errors!=null && tanUrlResponse.errors.size()>0){
            crpRequestLog.Solarisbank_Id__c=tanUrlResponse.errors.get(0).id;
            crpRequestLog.Object_Name__c='Account';
            crpRequestLog.Record_Id__c=sfId;
            crpRequestLog.Status__c='FAILED';
            crpRequestLog.Operation__c='Update Account Details';
            crpRequestLog.Description__c=tanUrlResponse.errors.get(0).title +' : '+tanUrlResponse.errors.get(0).detail;
            
        }
        else{
            crpRequestLog.Solarisbank_Id__c=tanUrlResponse.id;
            crpRequestLog.Object_Name__c='Account';
            crpRequestLog.Record_Id__c=sfId;
            crpRequestLog.Operation__c='Update Account Details';
            crpRequestLog.Status__c=tanUrlResponse.status;
            crpRequestLog.Updated_At__c=tanUrlResponse.updated_at;
            crpRequestLog.URL__c=tanUrlResponse.url;
            if(kycDetails.size()>0){
                kycDetails.get(0).Marital_Status__c=martialStatus;
                update kycDetails;
            }
             
            
        }
        
        insert crpRequestLog;
        return responseString;
    }
    
    @AuraEnabled
    public static void createTaxExemptionCase(String accountId,String bankAccountId,String subject,String description,String reason){
        List<Contact> contact=[SELECT id FROM Contact WHERE isPersonAccount=true and AccountId=:accountId LIMIT 1];
        List<Bank_Case_Item__c> bankCaseItems=new List<Bank_Case_Item__c>();
        Case newBankingCase=new Case();
        newBankingCase.recordTypeId=Constant.INVESTMENTCASE_CASE_RECORDTYPEID;
        newBankingCase.Status='NEW';
        newBankingCase.AccountId=accountId;
        newBankingCase.Origin='Web';
        newBankingCase.Priority='Low';
        newBankingCase.Type='Term Deposit';
        newBankingCase.Type_II__c=reason;
        newBankingCase.Reason=reason;
        newBankingCase.Subject=subject; 
        newBankingCase.Description=description;
        if(contact.size()>0) newBankingCase.ContactId=contact.get(0).Id;
        Database.DMLOptions dlo = new Database.DMLOptions();
        dlo.EmailHeader.triggerAutoResponseEmail = true;
        database.insert(newBankingCase, dlo);
         
        
        insert bankCaseItems;
        
        
    }
    
    private static Change_Request_Log__c generateChangeLog(String sbId,String sfId,String operation,String status,String details,String url,DateTime updateAt){
        Change_Request_Log__c changeRequestLog=new Change_Request_Log__c();
        changeRequestLog.Solarisbank_Id__c=sbId;
        changeRequestLog.Operation__c=operation;
        changeRequestLog.Object_Name__c='Account';
        changeRequestLog.Record_Id__c=sfId;
        changeRequestLog.Status__c=status;
        if(details!=null)changeRequestLog.Description__c=details;
        if(updateAt!=null)changeRequestLog.Updated_At__c=updateAt;
        if(url!=null)changeRequestLog.URL__c=url;
        return changeRequestLog;
    }
    
    
}