force-app/main/default/objects/Account/fields/Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Auth0 Identification</description>
    <externalId>true</externalId>
    <inlineHelpText>Auth0 Identification</inlineHelpText>
    <label>Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Latest_Evaluation_Date__c.field-meta.xml
<CustomField>
    <fullName>Latest_Evaluation_Date__c</fullName>
    <label>Latest Evaluation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Latest_Evaluation_Price__c.field-meta.xml
<CustomField>
    <fullName>Latest_Evaluation_Price__c</fullName>
    <label>Latest Evaluation Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Evaluation__c/Evaluation__c.object-meta.xml
<CustomObject>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>Eval{0000000}</displayFormat>
        <label>Evaluation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluation__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Evaluations</relationshipLabel>
    <relationshipName>Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solarisbank__c/Solarisbank__c.object-meta.xml
<CustomObject>
    <label>Solarisbank</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solarisbank</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solarisbank__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Solarisbank</relationshipLabel>
    <relationshipName>Solarisbank</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solarisbank__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OpportuntiyRealEstateService.cls
public with sharing class OpportuntiyRealEstateService {
    
    
    //AIM : get current termdepost status
    @AuraEnabled
    public static Boolean getTermDepositeStatus(String recordId){
        List<Opportunity> opp=[SELECT Id, AccountId,Account.Solarisbank_Tenent__c,Account.Auth0_ID__c ,Account.Solarisbank_Id__c,Account.PersonEmail,Account.Name FROM Opportunity WHERE id=:recordId];
        if(opp.size()==0) return false;
        List<Solarisbank__c> sbList=[SELECT id,Name,Email__c,Solarisbank_Id__c,Is_Term_Deposit_Enabled__c FROM Solarisbank__c WHERE Account__c=:opp.get(0).AccountId];
        Solarisbank__c sbDetails=new Solarisbank__c();
        //create new sb details if doesnt exsist
        if(sbList.size()==0){
            sbDetails.Name=opp.get(0).Account.Name;
            sbDetails.Account__c=opp.get(0).AccountId;
            sbDetails.Solarisbank_Id__c=opp.get(0).Account.Solarisbank_Id__c;
            sbDetails.Email__c=opp.get(0).Account.PersonEmail;
            sbDetails.Is_Term_Deposit_Enabled__c=false;
            insert sbDetails;
        }
        else{
          sbDetails=sbList.get(0);  
        } 
        
        return sbDetails.Is_Term_Deposit_Enabled__c;
    }
    
    //AIM : toggle term deposit tag on auth0 user
    @AuraEnabled
    public static Boolean toggleTermDepostForUser(String recordId,Boolean status){
        Boolean changedStatusFlag=false;
        List<Opportunity> opp=[SELECT Id, AccountId,Account.Solarisbank_Tenent__c,Account.Auth0_ID__c ,Account.Solarisbank_Id__c,Account.PersonEmail,Account.Name FROM Opportunity WHERE id=:recordId];
        if(opp.size()==0) return false;
        List<Solarisbank__c> sbList=[SELECT id,Name,Email__c,Term_Deposit_Enabled_At__c,Solarisbank_Id__c,Is_Term_Deposit_Enabled__c FROM Solarisbank__c WHERE Account__c=:opp.get(0).AccountId];
        Solarisbank__c sbDetails=new Solarisbank__c();
        if(sbList.size()>0) sbDetails = sbList.get(0);
        LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(opp.get(0).Id,'Opportunity',opp.get(0).Account.Solarisbank_Tenent__c);

        String responseJson = Auth0Service.updateUserDetails(opp.get(0).Account.Auth0_ID__c,'{ "user_metadata": { "term_deposit_enabled":'+status+' } }',apiCallDetails);
        Auth0Wrapper userDetails = Auth0Wrapper.parse(responseJson);
        
        //create new sb details if doesnt exsist
        if(sbList.size()==0){
            System.debug('sbList '+sbList.size());
            sbDetails.Name=opp.get(0).Account.Name;
            sbDetails.Account__c=opp.get(0).AccountId;
            sbDetails.Solarisbank_Id__c=opp.get(0).Account.Solarisbank_Id__c;
            sbDetails.Email__c=opp.get(0).Account.PersonEmail;
            sbDetails.Is_Term_Deposit_Enabled__c=false;
            insert sbDetails;
        }
         
        System.debug('sbDetails '+sbDetails);
        if(userDetails.user_metadata.term_deposit_enabled == status){
            sbDetails.Is_Term_Deposit_Enabled__c = status;
            sbDetails.Term_Deposit_Enabled_At__c = DateTime.now();
            update sbDetails;
            changedStatusFlag = true;
        }
        
        return changedStatusFlag;
        
    }
    
    //AIM : Retrive real estate email template desing
    @AuraEnabled
    public static Map<String,String> getRealEstateSaleEmailPreview(Id recordId){
        List<Opportunity> realEstateSale=[SELECT id,Asset__c,RecordTypeId FROM Opportunity WHERE id=:recordId];
        setAssetEvaluationDateToCurrentMonth(realEstateSale.get(0).Asset__c);
        String emailTo=getSentToEmail(realEstateSale.get(0).RecordTypeId); 
        String s='';
        EmailTemplate template=[SELECT Id, Name, Subject, HtmlValue FROM EmailTemplate where id=:Constant.OPPORTUNITY_REAL_ESTATE_SALE_EMAILTEMPLATE];
        s=MailUtill.proccessEmailTemplate(template.HtmlValue, true, recordId.getSobjectType().getDescribe().getName(), recordId);
        return new Map<String,String>{'BODY'=>s,'SUBJECT'=>template.Subject,'EMAIL'=>emailTo};
    }

	//AIM: send email to ev smartmoney team with email details    
    @AuraEnabled
    public static void sendEmailToAgent(String body,String subject,String recordId,String emailTo){
        MailUtill.sendPlainHtmlEmail(subject, body,emailTo, Constant.EV_SUPPORT_OWD_EMAIL, recordId);
    }

    //retirve email template 
    private static String getSentToEmail(String recordTypeId){
        String urlVariable='';
        String emailAddress='';
        
        if(recordTypeId==Constant.OPPORTUNITY_RE_PARTIALSALE_RECORDTYPEID)urlVariable='RealEstateOpportunityPartialSaleEmail';
        else if(recordTypeId==Constant.OPPORTUNITY_RE_VALUATION_RECORDTYPEID)urlVariable='RealEstateOpportunityValuationEmail';
        else if(recordTypeId==Constant.OPPORTUNITY_RE_FULLSALE_RECORDTYPEID)urlVariable='RealEstateOpportunityFullSaleEmail';
        List<Constant__mdt> value=[SELECT id,Value__c FROM Constant__mdt WHERE DeveloperName=:urlVariable];
        if(value.size()>0) emailAddress=value.get(0).Value__c;
        return emailAddress;
    }
    
    //update evaluation dates to latest
    private static void setAssetEvaluationDateToCurrentMonth(String assetId ){
       	Boolean doUpdate=false;
        List<Asset> realEstate=[SELECT Id, Latest_Evaluation_Date__c, Latest_Evaluation_Price__c,(SELECT id,Date__c,Value__c FROM Evaluations__r) FROM Asset WHERE id=:assetId];
        if(realEstate.size()>0){
            if(realEstate.get(0).Latest_Evaluation_Date__c==null || realEstate.get(0).Latest_Evaluation_Date__c.month()!=Date.Today().Month()){
                for(Evaluation__c evaluation:realEstate.get(0).Evaluations__r){
                    if(evaluation.Date__c.month()==Date.Today().Month()-1 && evaluation.Date__c.year()==Date.today().Year()){
                        realEstate.get(0).Latest_Evaluation_Date__c=evaluation.Date__c;
                        realEstate.get(0).Latest_Evaluation_Price__c=evaluation.Value__c;
                        doUpdate=true;
                    }
                }                	
            }
        }
        if(doUpdate) update realEstate;
    }
}