force-app/main/default/objects/Account/fields/Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Auth0 Identification</description>
    <externalId>true</externalId>
    <inlineHelpText>Auth0 Identification</inlineHelpText>
    <label>Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account IBAN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CHECKING_PERSONAL</fullName>
                <label>Checking Personal</label>
            </value>
            <value>
                <fullName>CHECKING_BUSINESS</fullName>
                <label>Checking Business</label>
            </value>
            <value>
                <fullName>CALL_MONEY</fullName>
                <label>Call Money</label>
            </value>
            <value>
                <fullName>TERM_DEPOSIT</fullName>
                <label>Term Deposit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>Booking-{00000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TaxExemptionFormControllerTest.cls
@isTest
public class TaxExemptionFormControllerTest {
    
    @isTest
    static void getPersonAccountRecordTypeIdTest(){
        TaxExemptionFormController.getPersonAccountRecordTypeId();
    }
    
    @isTest
    static void getCustomerDetailsTest(){
        Account a=TestDataFactory.getPersonAccount(true);
        Bank_Account__c ba=TestDataFactory.getBankAccount(a.id,false);
        ba.Type__c='TERM_DEPOSIT';
        insert ba;
        Booking__c booking=TestDataFactory.getBooking(ba.Id,true);
        Test.startTest();
        TaxExemptionFormController.getCustomerDetails(a.Solarisbank_Id__c, a.Auth0_ID__c,ba.id);
        Test.stopTest();
    }
    
    @isTest
    static void initiateMFARequestTest(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCRPRequestWrapper.MockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Bank_Account__c ba=TestDataFactory.getBankAccount(a.id,false);
        ba.Type__c='TERM_DEPOSIT';
        insert ba;
        Test.startTest();
        TaxExemptionFormController.initiateMFARequest(a.Solarisbank_Id__c, a.id);
        Test.stopTest();
    }
    
    @isTest
    static void initiateCRPRequestTestSuccess(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCRPRequestWrapper.MockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Bank_Account__c ba=TestDataFactory.getBankAccount(a.id,false);
        ba.Type__c='TERM_DEPOSIT';
        insert ba;
        Test.startTest();
        TaxExemptionFormController.initiateCRPRequest(a.id, '{}');
        Test.stopTest();
    }
    @isTest
    static void initiateCRPRequestTestError(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCRPRequestWrapper.MockResponse(true));
        Account a=TestDataFactory.getPersonAccount(true);
        Bank_Account__c ba=TestDataFactory.getBankAccount(a.id,false);
        ba.Type__c='TERM_DEPOSIT';
        insert ba;
        Test.startTest();
        try{
        TaxExemptionFormController.initiateCRPRequest(a.id, '{}');
        }catch(Exception e){}
        Test.stopTest();
    }
    
    @isTest
    static void closeMFARequestTest(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCRPRequestWrapper.MockResponse(true));
        Account a=TestDataFactory.getPersonAccount(true);
        Bank_Account__c ba=TestDataFactory.getBankAccount(a.id,false);
        ba.Type__c='TERM_DEPOSIT';
        insert ba;
        Test.startTest();
        try{
        TaxExemptionFormController.closeMFARequest(a.Solarisbank_Id__c,'123', a.id);
        }catch(Exception e){}
        Test.stopTest();
    }
    
    @isTest
    static void closeCRPFRequestSuccess(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCRPRequestWrapper.MockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Bank__c b=TestDataFactory.getBankSolarisBank(a.id, true);
        Bank_Account__c ba=TestDataFactory.getBankAccount(a.id,false);
        ba.Type__c='TERM_DEPOSIT';
        insert ba;
        Test.startTest();
        TaxExemptionFormController.closeCRPFRequest(a.Id, 'https://ev-smartmoney.coom', '123', 'MARRIED');
        Test.stopTest();
    }
    @isTest
    static void closeCRPFRequestError(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCRPRequestWrapper.MockResponse(true));
        Account a=TestDataFactory.getPersonAccount(true);
        Bank_Account__c ba=TestDataFactory.getBankAccount(a.id,false);
        ba.Type__c='TERM_DEPOSIT';
        insert ba;
        Test.startTest();
        try{
        TaxExemptionFormController.closeCRPFRequest(a.Id, 'https://ev-smartmoney.coom', '123', 'MARRIED');
        }catch(Exception e){}
        Test.stopTest();
    }
    
    @isTest
    static void createTaxExemptionCaseTest(){
        Account a=TestDataFactory.getPersonAccount(true);
        Bank_Account__c ba=TestDataFactory.getBankAccount(a.id,false);
        ba.Type__c='TERM_DEPOSIT';
        insert ba;
        Test.startTest();
        TaxExemptionFormController.createTaxExemptionCase(a.Id, ba.Id, 'TaxExemption','Remove','Early Termination');
        Test.stopTest();
    }
}