force-app/main/default/objects/Account/fields/Birth_City__c.field-meta.xml
<CustomField>
    <fullName>Birth_City__c</fullName>
    <label>Birth City</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Berlin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Birth_Country__c.field-meta.xml
<CustomField>
    <fullName>Birth_Country__c</fullName>
    <label>Birth Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Birth_Name__c.field-meta.xml
<CustomField>
    <fullName>Birth_Name__c</fullName>
    <label>Birth Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Business_Purpose__c</fullName>
    <label>Business Purpose</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMPLOYED</fullName>
                <label>Employed</label>
            </value>
            <value>
                <fullName>UNEMPLOYED</fullName>
                <label>Unemployed</label>
            </value>
            <value>
                <fullName>PUBLIC_SECTOR_EMPLOYEE</fullName>
                <label>Public Sector Employee</label>
            </value>
            <value>
                <fullName>PROFESSIONAL_SOLDIER</fullName>
                <label>Professional Soldier</label>
            </value>
            <value>
                <fullName>FREELANCER</fullName>
                <label>Freelancer</label>
            </value>
            <value>
                <fullName>HOUSEWORK</fullName>
                <label>Housework</label>
            </value>
            <value>
                <fullName>APPRENTICE</fullName>
                <label>Apprentice</label>
            </value>
            <value>
                <fullName>MANAGEMENT</fullName>
                <label>Management</label>
            </value>
            <value>
                <fullName>RETIRED</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>STUDENT</fullName>
                <label>Student</label>
            </value>
            <value>
                <fullName>SELF_EMPLOYED</fullName>
                <label>Self Employed</label>
            </value>
            <value>
                <fullName>MILITARY_OR_COMMUNITY_SERVICE</fullName>
                <label>Military Or Community Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fatca_Crs_Confirmed_At__c.field-meta.xml
<CustomField>
    <fullName>Fatca_Crs_Confirmed_At__c</fullName>
    <label>Fatca Crs Confirmed At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fatca_Relevant__c.field-meta.xml
<CustomField>
    <fullName>Fatca_Relevant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fatca Relevant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Flagged_By_Compliance__c.field-meta.xml
<CustomField>
    <fullName>Flagged_By_Compliance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flagged By Compliance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Key__c.field-meta.xml
<CustomField>
    <fullName>Industry_Key__c</fullName>
    <label>Industry Key</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUILDING_INDUSTRY</fullName>
                <label>Building Industry</label>
            </value>
            <value>
                <fullName>TRADE_MAINTENANCE_AND_REPAIR_OF_VEHICLES</fullName>
                <label>Trade Maintenance And Repair Of Vehicles</label>
            </value>
            <value>
                <fullName>OTHER_SERVICES</fullName>
                <label>Other Services</label>
            </value>
            <value>
                <fullName>GASTRONOMY</fullName>
                <label>Gastronomy</label>
            </value>
            <value>
                <fullName>SCIENTIFIC_TECHNICAL_CONSULTING_SERVICES</fullName>
                <label>Scientific Technical Consulting Services</label>
            </value>
            <value>
                <fullName>INFORMATION_AND_COMMUNICATION</fullName>
                <label>Information And Communication</label>
            </value>
            <value>
                <fullName>OTHER_ECONOMIC_SERVICES</fullName>
                <label>Other Economic Services</label>
            </value>
            <value>
                <fullName>FARMER_FORESTRY_FISHING_AND_AQUACULTURE</fullName>
                <label>Farmer Forestry Fishing And Aquaculture</label>
            </value>
            <value>
                <fullName>POWER_WATER_SUPPLY_DISPOSAL_MINING</fullName>
                <label>Power Water Supply Disposal Mining</label>
            </value>
            <value>
                <fullName>CHEMICAL_INDUSTRY_COKE_OVEN_MINERAL_OIL</fullName>
                <label>Chemical Industry Coke Oven Mineral Oil</label>
            </value>
            <value>
                <fullName>MANUFACTURE_PLASTICS_RUBBER_GOODS</fullName>
                <label>Manufacture Plastics Rubber Goods</label>
            </value>
            <value>
                <fullName>STONE_SOIL_CERAMICS_GLASS</fullName>
                <label>Stone Soil Ceramics Glass</label>
            </value>
            <value>
                <fullName>METAL_PRODUCTION_PROCESSING</fullName>
                <label>Metal Production Processing</label>
            </value>
            <value>
                <fullName>MECHANICAL_ENGINEERING_VEHICLE_MANUFACTURING</fullName>
                <label>Mechanical Engineering Vehicle Manufacturing</label>
            </value>
            <value>
                <fullName>MANUFACTURE_DATA_PROC_EQUIPMENT_ELECTRIC_OPTICS</fullName>
                <label>Manufacture Data Proc Equipment Electric Optics</label>
            </value>
            <value>
                <fullName>WOOD_PAPER_PRINT_INDUSTRY_FURNITURE_ETC</fullName>
                <label>Wood Paper Print Industry Furniture Etc</label>
            </value>
            <value>
                <fullName>LEATHER_TEXTILE_CLOTHES_INDUSTRY</fullName>
                <label>Leather Textile Clothes Industry</label>
            </value>
            <value>
                <fullName>FOOD_INDUSTRY_TOBACCO_PRODUCTS</fullName>
                <label>Food Industry Tobacco Products</label>
            </value>
            <value>
                <fullName>TRANSPORT_AND_STORAGE_AND_NEWS_TRANSMISSION</fullName>
                <label>Transport And Storage And News Transmission</label>
            </value>
            <value>
                <fullName>FINANCIAL_LEASING_COMPANIES</fullName>
                <label>Financial Leasing Companies</label>
            </value>
            <value>
                <fullName>FINANCIAL_INSTITUTIONS_INSURANCE</fullName>
                <label>Financial Institutions Insurance</label>
            </value>
            <value>
                <fullName>HOLDING_COMPANIES</fullName>
                <label>Holding Companies</label>
            </value>
            <value>
                <fullName>HOUSING_COMPANIES</fullName>
                <label>Housing Companies</label>
            </value>
            <value>
                <fullName>OTHER_PROPERTY_MANAGEMENT</fullName>
                <label>Other Property Management</label>
            </value>
            <value>
                <fullName>HEALTH_CARE_VETERIN_A_WELFARE_FIRM_FREELANCE</fullName>
                <label>Health Care Veterin A Welfare Firm Freelance</label>
            </value>
            <value>
                <fullName>LEASING_OF_MOVABLE_OBJECTS</fullName>
                <label>Leasing Of Movable Objects</label>
            </value>
            <value>
                <fullName>NONE</fullName>
                <label>None</label>
            </value>
            <value>
                <fullName>ECONOMICALLY_DEPENDENT_INDIVIDUALS</fullName>
                <label>Economically Dependent Individuals</label>
            </value>
            <value>
                <fullName>OTHER_PERSONAL_SERVICE_ACTIVITIES</fullName>
                <label>Other Personal Service Activities</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <label>Legal Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SINGLE</fullName>
                <label>Single</label>
            </value>
            <value>
                <fullName>MARRIED</fullName>
                <label>Married</label>
            </value>
            <value>
                <fullName>DIVORCED</fullName>
                <label>Divorced</label>
            </value>
            <value>
                <fullName>UNKNOWN</fullName>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Own_Economic_Interest_Signed_At__c.field-meta.xml
<CustomField>
    <fullName>Own_Economic_Interest_Signed_At__c</fullName>
    <label>Own Economic Interest Signed At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Tax_Assessment__c</fullName>
    <label>Tax Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SEPARATE</fullName>
                <label>Separate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Terms_Conditions_Signed_At__c.field-meta.xml
<CustomField>
    <fullName>Terms_Conditions_Signed_At__c</fullName>
    <label>Bank Terms Conditions Signed At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Identification__c/Identification__c.object-meta.xml
<CustomObject>
    <label>Identification</label>
    <nameField>
        <displayFormat>Identification-{00000}</displayFormat>
        <label>Identification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Identification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Person_Identifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AccountService.cls
public with Sharing class AccountService {
    
    
    @AuraEnabled
    public static String createNewIdentification(String recordId,String languageCode){
        List<Account> accountDetailList= [SELECT Id, Name, Solarisbank_Id__c,Solarisbank_Tenent__c
                                          FROM Account
                                          WHERE id=:recordId];
        if(accountDetailList.size()==0) return null;
        Account accountDetals=accountDetailList.get(0);
        LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(recordId,'Account',accountDetals.Solarisbank_Tenent__c);
        String requestBody='{"method": "idnow","language": "'+languageCode+'"}';
        String res=SolarisbankService.createNewIdentificationAttempt(accountDetals.Solarisbank_Id__c,requestBody,apiCallDetails);
        SolarisBankIdentificationWrapper response=SolarisBankIdentificationWrapper.parse(res);
        if(String.isNotEmpty(response.id)){
            LogService.ApiCallDetails apiCallDetailsForIdent =  new LogService.ApiCallDetails(recordId,'Account',accountDetals.Solarisbank_Tenent__c);
            String responseString=SolarisbankService.fetchIdentificationRequestDetails(accountDetals.Solarisbank_Id__c,response.id,apiCallDetailsForIdent);
            SolarisBankIdentificationWrapper identResponse=SolarisBankIdentificationWrapper.parse(responseString);
            
            Identification__c newIdentification=new Identification__c();
            newIdentification.Solarisbank_Id__c=identResponse.id;      
            newIdentification.Method__c='IDnow';
            newIdentification.Account__c=accountDetals.id;
            newIdentification.RecordTypeId=Constant.IDENTIFIACTION_VIDEO_IDENTIFICATION_RECORDTYPEID;
            if(String.isNotEmpty(identResponse.url)) newIdentification.URL__c=identResponse.url;
            if(String.isNotEmpty(identResponse.reference)) newIdentification.Reference__c=identResponse.reference;
            insert newIdentification; 
        }
        
        return String.isNotEmpty(response.id)?response.id:response.failure_reason;
        
    } 
    
    @AuraEnabled
    public static void syncPersonDetailsWithSB(String sfAccountId){
        Account sfAccount=[SELECT Id,LastName,Salutation,Gender__pc,FirstName,Legal_Name__c,
                           Own_Economic_Interest_Signed_At__c,Flagged_By_Compliance__c,
                           Terms_Conditions_Signed_At__c,Industry_Key__c,Industry,Solarisbank_Tenent__c,Solarisbank_Id__c,
                           Business_Purpose__c,Fatca_Crs_Confirmed_At__c,Fatca_Relevant__c,Marital_Status__c,Tax_Assessment__c,PersonTitle,Birth_Country__c,Nationality__c,Employment_Status__c,
                           PersonEmail,PersonMobilePhone,PersonBirthdate,Birth_Name__c,Birth_City__c,
                           ShippingState,ShippingCountry,ShippingCity,ShippingPostalCode,ShippingStreet,BillingState,BillingStreet,BillingPostalCode,BillingCity,BillingCountry
                           FROM Account WHERE id=:sfAccountId LIMIT 1];
        LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(sfAccount.Id,'Account',sfAccount.Solarisbank_Tenent__c);
        //checking if solaribank id exsisitngs
        if(String.isNotEmpty(sfAccount.Solarisbank_Id__c)){
            //fetching person account details
            String personJson=SolarisbankService.fetchPersonDetails(sfAccount.Solarisbank_Id__c,apiCallDetails);
            SolarisbankPersonWrapper personDetails=SolarisbankPersonWrapper.parse(personJson);
            if(personDetails.last_name == null) return ;
            //fetching phone number
            String phoneJson=SolarisbankService.fetchPersonPhoneNumber(sfAccount.Solarisbank_Id__c,apiCallDetails);
            Map<String,Object> phoneJsonMap=(Map<String,Object>) JSON.deserializeUntyped(phoneJson);
            //operation
            if(sfAccount.Salutation==null || sfAccount.Salutation!=personDetails.salutation)sfAccount.Salutation = personDetails.salutation;
            sfAccount.Gender__pc=(personDetails.salutation=='MR')?'Male':'Female';
            if(sfAccount.FirstName==null)sfAccount.FirstName = personDetails.first_name;
            
            if(sfAccount.LastName==null)sfAccount.LastName = personDetails.last_name;
            sfAccount.Legal_Name__c = personDetails.first_name+' '+ personDetails.last_name;
            if(personDetails.address != null && sfAccount.BillingStreet !=  personDetails.address.line_1)  sfAccount.BillingStreet =  personDetails.address.line_1;
            if(personDetails.address != null && sfAccount.BillingPostalCode != personDetails.address.postal_code) sfAccount.BillingPostalCode = personDetails.address.postal_code;
            if(personDetails.address != null && sfAccount.BillingCity != personDetails.address.city) sfAccount.BillingCity = personDetails.address.city;
            if(personDetails.address != null && sfAccount.BillingCountry !=  personDetails.address.country) sfAccount.BillingCountry =  personDetails.address.country;
            if(personDetails.address != null && sfAccount.BillingState !=  personDetails.address.state) sfAccount.BillingState =  personDetails.address.state;
            if(personDetails.contact_address != null && sfAccount.ShippingStreet !=  personDetails.contact_address.line_1) sfAccount.ShippingStreet =  personDetails.contact_address.line_1;
            if(personDetails.contact_address != null && sfAccount.ShippingPostalCode != personDetails.contact_address.postal_code) sfAccount.ShippingPostalCode = personDetails.contact_address.postal_code;
            if(personDetails.contact_address != null && sfAccount.ShippingCity != personDetails.contact_address.city) sfAccount.ShippingCity = personDetails.contact_address.city;
            if(personDetails.contact_address != null && sfAccount.ShippingCountry !=  personDetails.contact_address.country) sfAccount.ShippingCountry =  personDetails.contact_address.country;
            if(personDetails.contact_address != null && sfAccount.ShippingState !=  personDetails.contact_address.state) sfAccount.ShippingState =  personDetails.contact_address.state;
            if(personDetails.email != null && sfAccount.PersonEmail !=  personDetails.email)sfAccount.PersonEmail=personDetails.email;
            
            if(personDetails.mobile_number!=null && sfAccount.PersonMobilePhone  != personDetails.mobile_number) sfAccount.PersonMobilePhone  = personDetails.mobile_number;
            if(phoneJsonMap.containsKey('number'))  sfAccount.Phone=(String)phoneJsonMap.get('number'); 
             if(personDetails.birth_name!=null && sfAccount.Birth_Name__c  != personDetails.birth_name) sfAccount.Birth_Name__c= personDetails.birth_name;
            if(personDetails.birth_city!=null && sfAccount.Birth_City__c  != personDetails.birth_city) sfAccount.Birth_City__c=personDetails.birth_city;
            if(personDetails.birth_country!=null && sfAccount.Birth_Country__c  != personDetails.birth_country) sfAccount.Birth_Country__c =personDetails.birth_country;
            if(personDetails.nationality!=null && sfAccount.Nationality__c  != personDetails.nationality)sfAccount.Nationality__c  = personDetails.nationality;
            if(personDetails.employment_status!=null && sfAccount.Employment_Status__c  != personDetails.employment_status)sfAccount.Employment_Status__c = personDetails.employment_status;
            if(personDetails.title!=null && sfAccount.PersonTitle != personDetails.title) sfAccount.PersonTitle = personDetails.title;
            if(personDetails.tax_information!=null && sfAccount.Tax_Assessment__c!= personDetails.tax_information.tax_assessment) sfAccount.Tax_Assessment__c= personDetails.tax_information.tax_assessment;
            if(personDetails.tax_information!=null && sfAccount.Marital_Status__c!=  personDetails.tax_information.marital_status) sfAccount.Marital_Status__c=  personDetails.tax_information.marital_status;
            if(personDetails.fatca_relevant!=null && sfAccount.Fatca_Relevant__c !=personDetails.fatca_relevant) sfAccount.Fatca_Relevant__c =personDetails.fatca_relevant;
             if(personDetails.business_purpose!=null && sfAccount.Business_Purpose__c !=personDetails.business_purpose)sfAccount.Business_Purpose__c = personDetails.business_purpose;
            if(personDetails.industry!=null && sfAccount.Industry !=personDetails.industry)sfAccount.Industry = personDetails.industry;
            if(personDetails.industry_key!=null && sfAccount.Industry_Key__c !=personDetails.industry_key)sfAccount.Industry_Key__c = personDetails.industry_key;
             if(personDetails.flagged_by_compliance!=null)sfAccount.Flagged_By_Compliance__c =personDetails.flagged_by_compliance;
             update sfAccount;
        }
        
    }
}