force-app/main/default/objects/Account/fields/EVSM_Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>EVSM_Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>EVSM Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Money_Transferred__c.field-meta.xml
<CustomField>
    <fullName>Is_Money_Transferred__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Money Transferred</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Money_Transfer_Confirmed_By__c.field-meta.xml
<CustomField>
    <fullName>Money_Transfer_Confirmed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Money Transfer Confirmed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportuntiyInvestmentService.cls
public class  OpportuntiyInvestmentService {
    
    @AuraEnabled
    public static void sendMoneyTransferConformation(String oppId){
        try{         
            Opportunity oppDetails=[SELECT Id,External_Id__c ,Account.EVSM_Auth0_Id__c,Account.Solarisbank_Tenent__c,Is_Money_Transferred__c, Money_Transfer_Confirmed_By__c FROM Opportunity WHERE id=:oppId];
            if(!oppDetails.Is_Money_Transferred__c && String.isNotEmpty(oppDetails.External_Id__c) && oppDetails.External_Id__c!=null){
                LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(oppDetails.Id,'Opportunity',oppDetails.Account.Solarisbank_Tenent__c);
                DateTime dt=DateTime.now();
                DateTime dtGmt=Datetime.valueOfGmt(String.valueOf(dt));
                String gmtDTString=JSON.serialize(dtGmt);
                String body='{"moneyTransferred":true,"moneyTransferredAt":'+gmtDTString+'}';
                String statusResponse=EVExternalService.updateInvestmentUpdate(oppDetails.External_Id__c,oppDetails.Account.EVSM_Auth0_Id__c,body,apiCallDetails);
                oppDetails.Is_Money_Transferred__c=true;
                oppDetails.Money_Transfer_Confirmed_By__c=Userinfo.getUserId();
                oppDetails.StageName='WAIT_FOR_START_DATE';
                update oppDetails;
            }
        }
        catch(Exception e){
            String index = logError(e,oppId,'Opportunity','OpportuntiyInvestmentService','sendMoneyTransferConformation','SMI Money Transfer Conformation');
            throw new AuraHandledException('Please contact your System admin.And provide '+index+' id to resolve issue.');
        }
    }
    
    
     @AuraEnabled
    public static void sendInvestmentStatus(String oppId){
        try{         
            Opportunity oppDetails=[SELECT Id,StageName,Account.EVSM_Auth0_Id__c,External_Id__c,Account.Solarisbank_Tenent__c FROM Opportunity WHERE id=:oppId];
            if(String.isNotEmpty(oppDetails.External_Id__c) && oppDetails.External_Id__c!=null){
                LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(oppDetails.Id,'Opportunity',oppDetails.Account.Solarisbank_Tenent__c);
                DateTime dt=DateTime.now();
                DateTime dtGmt=Datetime.valueOfGmt(String.valueOf(dt));
                String gmtDTString=JSON.serialize(dtGmt);
                String body='{"status":"'+oppDetails.StageName+'"}';
                String statusResponse=EVExternalService.updateInvestmentUpdate(oppDetails.External_Id__c,oppDetails.Account.EVSM_Auth0_Id__c,body,apiCallDetails);
            }
            
        }
        catch(Exception e){
            String index = logError(e,oppId,'Opportunity','OpportuntiyInvestmentService','sendInvestmentStatus','SMI Send Stage');
        }
    }
    
    
    //helper
    private static String logError(Exception e,String recordID,String objectName,String componentName,String methodName,String operation){
        LogService.LogMetadata details=new LogService.LogMetadata();
        details.addError(e);
        details.addRecordInfo(objectName,recordId);
        
        details.addMetadataInfo(userinfo.getUserId(),'SMI_OpportuntiyInvestmentService', methodName, componentName, operation);
        return LogService.logError(details);
    }
}