force-app/main/default/objects/Account/fields/EVSM_Auth0_ID__c.field-meta.xml
<CustomField>
    <fullName>EVSM_Auth0_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>EVSM Auth0 ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Classification__c/Customer_Classification__c.object-meta.xml
<CustomObject>
    <label>Customer Classification</label>
    <nameField>
        <displayFormat>Classification-{00000}</displayFormat>
        <label>Classification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Classification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Qualifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Classification__c/fields/System_Status__c.field-meta.xml
<CustomField>
    <fullName>System_Status__c</fullName>
    <label>System Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ONGOING</fullName>
            </value>
            <value>
                <fullName>ONGOING_ADDITIONAL_QUESTIONS</fullName>
            </value>
            <value>
                <fullName>ONGOING_AUTOMATIC_DECLINED</fullName>
            </value>
            <value>
                <fullName>ONGOING_AUTOMATIC_APPROVED</fullName>
            </value>
            <value>
                <fullName>INTERNAL_AUTOMATIC_DECLINED</fullName>
            </value>
            <value>
                <fullName>AWAITING_INTERNAL_PROCESSING</fullName>
            </value>
            <value>
                <fullName>INTERNAL_MANUALLY_APPROVED</fullName>
            </value>
            <value>
                <fullName>INTERNAL_MANUALLY_DECLINED</fullName>
            </value>
            <value>
                <fullName>AWAITING_PARTNER_PROCESSING</fullName>
            </value>
            <value>
                <fullName>PARTNER_MANUALLY_APPROVED</fullName>
            </value>
            <value>
                <fullName>PARTNER_MANUALLY_DECLINED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerClassificationService.cls
public with sharing class CustomerClassificationService {

    @AuraEnabled
    public static void updateSystemStatusToExternalSystem(String customerClassificationId){
        try{
            Customer_Classification__c classification=[SELECT Id,RecordType.DeveloperName,Account__r.EVSM_Auth0_ID__c,Account__r.Solarisbank_Tenent__c, Account__c, External_Id__c, System_Status__c FROM Customer_Classification__c WHERE id=:customerClassificationId];
            if(String.isNotEmpty(classification.External_Id__c) && classification.External_Id__c!=null){
                LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(classification.Id,'Customer_Classification__c',classification.Account__r.Solarisbank_Tenent__c);
                
                String body='{"status":"'+classification.System_Status__c+'"}';
                String statusResponse=EVExternalService.updateCustomerClassificationUpdate(classification.External_Id__c,classification.Account__r.EVSM_Auth0_ID__c,body,apiCallDetails);
            }
             

        }
        Catch(Exception e){
           logError('Customer_Classification__c',customerClassificationId,e,'updateSystemStatusToExternalSystem','Customer Classification - Update - Set System Status','Send Customer Classification Data To BE');
        }
        
    }
    
    @testVisible
    private static void logError(String objectName,String recordId,Exception e,String methodName,String componentName,String operation){
        LogService.LogMetadata errorDetails=new LogService.LogMetadata();
        errorDetails.addError(e);
        errorDetails.addRecordInfo(objectName,recordId);
        errorDetails.addMetadataInfo(userinfo.getUserId(), 'CustomerClassificationService', methodName, componentName,operation);
        LogService.logError(errorDetails);
    }
}