force-app/main/default/objects/Account/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account IBAN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <label>Person_Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>NO_BLOCK</fullName>
                <label>No Block</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CHECKING_PERSONAL</fullName>
                <label>Checking Personal</label>
            </value>
            <value>
                <fullName>CHECKING_BUSINESS</fullName>
                <label>Checking Business</label>
            </value>
            <value>
                <fullName>CALL_MONEY</fullName>
                <label>Call Money</label>
            </value>
            <value>
                <fullName>TERM_DEPOSIT</fullName>
                <label>Term Deposit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/Bank_Case_Item__c.object-meta.xml
<CustomObject>
    <label>Bank Case Item</label>
    <nameField>
        <displayFormat>Bank Case Item-{00000}</displayFormat>
        <label>Bank Case Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Case Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Case_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Bank Case Items</relationshipLabel>
    <relationshipName>Bank_Case_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Identification__c.field-meta.xml
<CustomField>
    <fullName>Identification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Identification</label>
    <referenceTo>KYC_Detail__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Scheduled_Order__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Order</label>
    <referenceTo>Scheduled_Order__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Bank_Case_Item__c/recordTypes/Card.recordType-meta.xml
<RecordType>
    <fullName>Card</fullName>
    <active>true</active>
    <label>Card</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>Booking-{00000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Card Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Name_On_Card__c.field-meta.xml
<CustomField>
    <fullName>Name_On_Card__c</fullName>
    <label>Name On Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Card_Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MASTERCARD_DEBIT</fullName>
                <label>Mastercard Debit</label>
            </value>
            <value>
                <fullName>VISA_DEBIT</fullName>
                <label>Visa Debit</label>
            </value>
            <value>
                <fullName>MASTERCARD_BUSINESS_DEBIT</fullName>
                <label>Mastercard Business Debit</label>
            </value>
            <value>
                <fullName>VISA_BUSINESS_DEBIT</fullName>
                <label>Visa Business Debit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Identification__c/Identification__c.object-meta.xml
<CustomObject>
    <label>Identification</label>
    <nameField>
        <displayFormat>Identification-{00000}</displayFormat>
        <label>Identification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Identification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Person_Identifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>Reservation Number-{00000000}</displayFormat>
        <label>Reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPEN</fullName>
                <label>Open</label>
            </value>
            <value>
                <fullName>RESOLVED</fullName>
                <label>Resolved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Order__c/Scheduled_Order__c.object-meta.xml
<CustomObject>
    <label>Scheduled Order</label>
    <nameField>
        <displayFormat>SO-{0000000}</displayFormat>
        <label>Scheduled Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Order__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipName>Scheduled_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Order__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Subscription-{00000}</displayFormat>
        <label>Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Newsletter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <label>Lead</label>
</RecordType>

force-app/main/default/globalValueSets/Card_Status_Values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PROCESSING</fullName>
        <label>Processing</label>
    </customValue>
    <customValue>
        <fullName>ACTIVE</fullName>
        <label>Active</label>
    </customValue>
    <customValue>
        <fullName>INACTIVE</fullName>
        <label>Inactive</label>
    </customValue>
    <customValue>
        <fullName>BLOCKED</fullName>
        <label>Blocked</label>
    </customValue>
    <customValue>
        <fullName>BLOCKED_BY_SOLARIS</fullName>
        <label>Blocked By Solaris</label>
    </customValue>
    <customValue>
        <fullName>CLOSED</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>ACTIVATION_BLOCKED_BY_SOLARIS</fullName>
        <label>Activation Blocked By Solaris</label>
    </customValue>
    <customValue>
        <fullName>CLOSED_BY_SOLARIS</fullName>
        <label>Closed By Solaris</label>
    </customValue>
    <masterLabel>Card Status Values</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {
     
    public static Lead getWebLead(Boolean doInsert){
        return generateLead(Constant.DEFAULT_LEAD_RECORDTYPEID,doInsert);
    }
    public static Account getPersonAccount(Boolean doInsert){
        return generateAccount(Constant.PERSON_ACCOUNT_RECORDTYPEID, doInsert);
    }
  
    public static Opportunity getStandardOpportunity(String accountId,Boolean doInsert){
        return generateOpportunity(Constant.STANDARD_OPPORTUNITY_RECORDTYPEID,accountId,doInsert);
    }
    public static Case getStandardCase(String accountId,Boolean doInsert){
        return generateCase(Constant.STANDARD_CASE_RECORDTYPEID, accountid, doInsert);
    }
     public static Case getBankCase(String accountId,Boolean doInsert){
        return generateCase(Constant.BANKINGCASE_CASE_RECORDTYPEID, accountid, doInsert);
    }
     public static Case getEVKontoCase(String accountId,Boolean doInsert){
        return generateCase(Constant.EVKONTOAPPCASE_CASE_RECORDTYPEID, accountid, doInsert);
    }
    public static Campaign getStandardCampaign(Boolean doInsert){
        return generateCampaing(Constant.STANDARD_CAMPAIGN_RECORDTYPEID,doInsert);
    }    
    public static Contentversion getContentVersion(Boolean doInsert){
        Contentversion cv=new Contentversion(Title = 'ABC',Type__c='Draft', PathOnClient = 'test', VersionData = EncodingUtil.base64Decode('Unit Test Attachment Body'));
        if(doInsert) insert cv;
        return  cv;
    }
    
    public static Contact getContact(Boolean doInsert){
        Contact c=new Contact();
        c.LastName=RandomUtil.randomString(6);
        if(doInsert) insert c;
        return c;
    }
    
    public static CampaignMember getLeadCampaignMember(String campaignId,String leadId,Boolean doInsert){
        CampaignMember cm=new CampaignMember();
        cm.LeadId=leadId;
        cm.CampaignId=campaignId;
        cm.Status='Sent';
        if(doInsert) insert cm;
        return cm;
            
    }
    public static CampaignMember getContactCampaignMember(String campaignId,String contactId,Boolean doInsert){
        CampaignMember cm=new CampaignMember();
        cm.ContactId=contactId;
        cm.CampaignId=campaignId;
        cm.Status='Sent';
        if(doInsert) insert cm;
        return cm;
            
    }
    public static Bank_Account__c getBankAccount(String accountId,Boolean doInsert){
        return generateBankAccount(accountId,doInsert);
    }
    public static Bank_Case_Item__c getAccountBankCase(String caseId,Boolean doInsert){
        return generateBankCase(Constant.BANKCASE_ACCOUNT_RECORDTYPEID,caseId,doInsert);
    }
    public static Bank_Case_Item__c getCardBankCase(String caseId,Boolean doInsert){
        return generateBankCase(Constant.BANKCASE_CARD_RECORDTYPEID,caseId,doInsert);
    }
    public static Bank_Case_Item__c getBookingBankCase(String caseId,Boolean doInsert){
        return generateBankCase(Constant.BANKCASE_BOOKING_RECORDTYPEID,caseId,doInsert);
    }
    public static Bank_Case_Item__c getBankAccountBankCase(String caseId,Boolean doInsert){
        return generateBankCase(Constant.BANKCASE_BANKACCOUNT_RECORDTYPEID,caseId,doInsert);
    }
     public static Bank_Case_Item__c getTimedOrderBankCase(String caseId,Boolean doInsert){
        return generateBankCase(Constant.BANKCASE_TIMEDGORDER_RECORDTYPEID,caseId,doInsert);
    }

    
    
    public static Card__c getCard(String accountId,String bankId,Boolean doInsert){
        Card__c card=new Card__c();
        card.name='434971******2356';
        card.Name_On_Card__c='NAME1 NAME2 SURNAME';
        card.Person_Account__c=accountId;
        card.Bank_Account__c=bankId;
        card.Solarisbank_Id__c='testcardeaea2acad1bcf119a9c0cfcboo';

        if(doInsert) insert card;
        return card;
    }
    public static Reservation__c getReservation(String bankId,Boolean doInsert){
        Reservation__c res=new Reservation__c();
        res.Bank_Account__c=bankId;
        res.Solarisbank_Id__c='088434f167eaea2acad1bcf119a9c0cfcboo';
        if(doInsert) insert res;
        return res;
    }
    
    public static Booking__c getBooking(String bankaccountId,Boolean doInsert){
        return generateBooking(bankaccountId,doInsert);
    }
    
    public static Scheduled_Order__c getTimedOrder(String bankaccountId,Boolean doInsert){
            return generateScheduledOrder(Constant.TIMED_SCHEDULEDORDER_RECORDTYPEID,bankaccountId,doInsert);
    }
    public static Scheduled_Order__c getStandingOrder(String bankaccountId,Boolean doInsert){
        
            return generateScheduledOrder(Constant.STANDING_SCHEDULEDORDER_RECORDTYPEID,bankaccountId,doInsert);
    }
    
    public static Identification__c getVideoIdentification(String accountId,Boolean doInsert){
        return genrateIdentification(accountId,Constant.IDENTIFIACTION_VIDEO_IDENTIFICATION_RECORDTYPEID,doInsert);
    }
    
    /*
    Generators
	*/
    
    private static Booking__c generateBooking(String bankaccountId,Boolean doInsert){
        Booking__c book=new Booking__c();
        book.Bank_Account__c=bankaccountId;
        book.Solarisbank_Id__c='088434f167eaea2acad1bcf119a9c0cfcboo';
        book.Transaction_Id__c='088434f167eaea2acad1bcf119a9c0cfcboo';
        if(doInsert) insert book;
        return book;
    }
    
    private static Scheduled_Order__c generateScheduledOrder(String recordTypeId,String bankaccountId,Boolean doInsert){
        Scheduled_Order__c order=new Scheduled_Order__c();
        order.recordTypeId=recordTypeId;
        order.Bank_Account__c=bankaccountId;
        order.Solarisbank_Id__c='088434f167eaea2acad1bcf119a9c0cfcboo';
        if(doInsert) insert order;
        return order;
    }
    
    private static Bank_Case_Item__c generateBankCase(String recordTypeId,String caseId,Boolean doInsert){
        Bank_Case_Item__c bc=new Bank_Case_Item__c();
        bc.RecordTypeId=recordTypeId;
        bc.Case__c=caseId;
        if(doInsert) insert bc;
        return bc;
    }
    
    private static Bank_Account__c generateBankAccount(Final String accountId,Boolean doInsert){
        Bank_Account__c ba=new Bank_Account__c();
        ba.Person_Account__c = accountId;
        ba.Name='DE98110101002528376528';
        ba.BIC__c='SOBKDEBBXXX';
        ba.Status__c='Active';
        ba.Solarisbank_Id__c='0652225cebcd3bec2c95ea8c461fe146cacc';
        if(doInsert ) insert ba;
        return ba;
    }
        
    private static Campaign generateCampaing(String recordTypeId,Boolean doInsert){
        Campaign c=new Campaign();
        c.Name=RandomUtil.randomString(3);
        c.Product__c='Newsletter';
        c.RecordTypeId=recordTypeId;
        if(doInsert) insert c;
        return c;
        
    }
    
    
    
    
    private static Lead generateLead(String recordtypeid,Boolean doInsert){
       
        
        Lead lead = new Lead();
        
        lead.Email = RandomUtil.randomString(3)+'@'+RandomUtil.randomString(4)+'.com';
        
        lead.State = 'New';
        lead.LastName = RandomUtil.randomString(4);
        lead.LeadSource = 'Website';
        lead.RecordTypeId = recordtypeid;
        lead.Website = 'www.'+RandomUtil.randomString(6)+'.com';
        if(doInsert) insert lead;
        return lead;
        
    }
    
    private static Account generateAccount(String recordtypeid,Boolean doInsert){
        
        Account account = new Account();
        account.PersonEmail= RandomUtil.randomString(3)+'@'+RandomUtil.randomString(4)+'.com';
        
        account.LastName = RandomUtil.randomString(4);
        account.RecordTypeId = recordtypeid;
        account.Solarisbank_Id__c='0652225cebcd3bec2c95ea8c461fe146cacc';
        account.Solarisbank_Tenent__c='Sandbox'; 
        if(doInsert) insert account;
        return account;
    }
    
    
    
    private static Opportunity generateOpportunity(Final String recordTypeId,Final String accountId,Final Boolean doInsert){
        Opportunity opp=new Opportunity();
        opp.Name=RandomUtil.randomString(4);
        opp.AccountId=accountId;
        opp.StageName='Qualifying';
        opp.CloseDate=Date.today()+10;
        opp.RecordTypeId=recordTypeId;
        if(doInsert) insert opp;
        return opp;
    }
    
    private static Case generateCase(String recordTypeId,String accountid,Boolean doInsert){
        Case c=new Case();
        c.RecordTypeId=recordTypeId;
        c.Status='New';
        c.Origin='Web';
		c.AccountId=accountid;
        if(doInsert) insert c;
        return c;
    }
    
    public static Subscription__c getNewsletterSubscription(String accountId,String contactId,Boolean doInsert){
        return generateSubscription(accountId,contactId,'Newsletter',Constant.SUBSCRIPTION_DEFAULT_RECORDTYPEID,doInsert);
    }
    
    private static Subscription__c generateSubscription(String accountId,String contactId,String subType,String recordTypeId,Boolean doInsert){
        Subscription__c newSubscriptionProduct=new Subscription__c();
        newSubscriptionProduct.Subscription_Status__c='Subscribed';
        newSubscriptionProduct.Type__c=subType;//'';
        newSubscriptionProduct.Account__c=accountId;
        
        newSubscriptionProduct.Send_Mail__c=false;
        newSubscriptionProduct.recordTypeId=recordTypeId;
        newSubscriptionProduct.Contact__c=contactId;
        if(doinsert) insert newSubscriptionProduct;
        return newSubscriptionProduct;
    }
    
    private static Identification__c genrateIdentification(String accountId,String recordTypeId,Boolean doInsert){
        Identification__c newIdentification=new Identification__c();
        newIdentification.Solarisbank_Id__c='testcardeaea2acad1bcf119a9c0cfcboo';      
        newIdentification.Account__c=accountId;
        newIdentification.RecordTypeId=recordTypeId;
        if(doInsert) insert newIdentification; 
        return newIdentification;
    }

}