force-app/main/default/objects/Account/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account IBAN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/Bank_Case_Item__c.object-meta.xml
<CustomObject>
    <label>Bank Case Item</label>
    <nameField>
        <displayFormat>Bank Case Item-{00000}</displayFormat>
        <label>Bank Case Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Case Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Case_Item__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Bank Case Items</relationshipLabel>
    <relationshipName>Bank_Case_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Scheduled_Order__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Order</label>
    <referenceTo>Scheduled_Order__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case_Item__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Bank_Case_Item__c/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/Bank_Case_Item__c/recordTypes/Card.recordType-meta.xml
<RecordType>
    <fullName>Card</fullName>
    <active>true</active>
    <label>Card</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>Booking-{00000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Card Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Verification__c/Case_Verification__c.object-meta.xml
<CustomObject>
    <label>Case Verification</label>
    <nameField>
        <displayFormat>Verification-{000000}</displayFormat>
        <label>Verification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Verifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Verification__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Verifications</relationshipLabel>
    <relationshipName>Case_Verifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>Reservation Number-{00000000}</displayFormat>
        <label>Reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Order__c/Scheduled_Order__c.object-meta.xml
<CustomObject>
    <label>Scheduled Order</label>
    <nameField>
        <displayFormat>SO-{0000000}</displayFormat>
        <label>Scheduled Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Order__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipName>Scheduled_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Order__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <label>Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Statement__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BankCaseOverrideControlerTest.cls
/***************
* @group Test Class
* @description test class for BankCaseOverrideControler
*/
@isTest
public class BankCaseOverrideControlerTest {

    
    
    @isTest
    static void testConstants(){ 
        BankCaseOverrideControler.getBankCaseTypes();
        BankCaseOverrideControler.getCaseIITypes();
        BankCaseOverrideControler.getCardStatusTypes();
        BankCaseOverrideControler.getScheludedOrderTypes();
        BankCaseOverrideControler.checkIsCompactLayout();
        BankCaseOverrideControler.getKYCPicklistValues();
    }
    
    @isTest
    static void testQuerys(){
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
     	Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case_Item__c cardBankCaseDetails=TestDataFactory.getCardBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Card__c=cardDetails.Id;
        insert cardBankCaseDetails;
        
        BankCaseOverrideControler.getCaseDetails(caseDetails.Id);
        BankCaseOverrideControler.fetchExsistingBankCases(caseDetails.Id);
        BankCaseOverrideControler.getBankCaseDetails(cardBankCaseDetails.Id);
        BankCaseOverrideControler.getBankAccounts(bankAccountDetails.Id);
        BankCaseOverrideControler.getAllBankCards(bankAccountDetails.Id);
        BankCaseOverrideControler.retriveBookings(bankAccountDetails.Id,null,null,null);
        BankCaseOverrideControler.retriveTimedOrders(bankAccountDetails.Id,null,null,null);
        BankCaseOverrideControler.retriveStandingOrders(bankAccountDetails.Id,null,null,null);
        BankCaseOverrideControler.retriveReservations(bankAccountDetails.Id,null,null,null);
        BankCaseOverrideControler.getAllIdentifications(accountDetails.Id);
        BankCaseOverrideControler.getSuccessKYCIdentificationRecord(accountDetails.id);
        
    }
    
    @isTest
    static void testGoogleApi(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCardWrapper.MockResponse());
        BankCaseOverrideControler.callGoogleMapSearchApi('Just So You Know','test');
        BankCaseOverrideControler.callGoogleMapsDetailsApi('Furqan Wrote this all','test');
    }
    
    @isTest
    static void testfetchTrasnsactionDetails(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCardWrapper.MockResponse());
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case_Item__c cardBankCaseDetails=TestDataFactory.getBookingBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Booking__c=booking.id;
        insert cardBankCaseDetails;
        Test.startTest();
        BankCaseOverrideControler.fetchTrasnsactionDetails(cardBankCaseDetails.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testretriveBalanceDetails(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCardWrapper.MockResponse());
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case_Item__c cardBankCaseDetails=TestDataFactory.getBankAccountBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Bank_Account__c=bankAccountDetails.id;
        insert cardBankCaseDetails;
        Test.startTest();
        BankCaseOverrideControler.retriveBalanceDetails(cardBankCaseDetails.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testStatmentRange(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCardWrapper.MockResponse());
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case_Item__c cardBankCaseDetails=TestDataFactory.getBankAccountBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Bank_Account__c=bankAccountDetails.id;
        insert cardBankCaseDetails;
        
        Statement__c state=New Statement__c();
        state.Bank_Account__c=bankAccountDetails.id;
        state.Solarisbank_Id__c='0652225cebcd3bec2c95ea8c461fe146cacc';
        Test.startTest();
        List<Bank_Account__c> baccounts=BankCaseOverrideControler.getBankAccounts(accountDetails.Id);
        BankCaseOverrideControler.createStatment(caseDetails.Id,baccounts.get(0),false,baccounts.get(0).Solarisbank_Id__c,'{}');
        BankCaseOverrideControler.fetchBankStatement(caseDetails.Id,baccounts.get(0),false,baccounts.get(0).Solarisbank_Id__c,state);

        Test.stopTest();

    }
    @isTest
    static void testStatmentPeriod(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCardWrapper.MockResponse());
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case_Item__c cardBankCaseDetails=TestDataFactory.getBankAccountBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Bank_Account__c=bankAccountDetails.id;
        insert cardBankCaseDetails;
        
        Statement__c state=New Statement__c();
        state.Bank_Account__c=bankAccountDetails.id;
        state.Solarisbank_Id__c='0652225cebcd3bec2c95ea8c461fe146cacc';
        Test.startTest();
        List<Bank_Account__c> baccounts=BankCaseOverrideControler.getBankAccounts(accountDetails.Id);
        BankCaseOverrideControler.createStatment(caseDetails.Id,baccounts.get(0),true,baccounts.get(0).Solarisbank_Id__c,'{}');
        BankCaseOverrideControler.fetchBankStatement(caseDetails.Id,baccounts.get(0),true,baccounts.get(0).Solarisbank_Id__c,state);
        Test.stopTest();

    }
    
    @isTest
    static void testrequestTransactionDetails(){
         Test.setMock(HttpCalloutMock.class, new SolarisbankBookingsWrapper.MockResponse());
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case_Item__c cardBankCaseDetails=TestDataFactory.getBookingBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Booking__c=booking.id;
        insert cardBankCaseDetails;
        
        
        Test.startTest();
        List<Bank_Account__c> baccounts=BankCaseOverrideControler.getBankAccounts(accountDetails.Id);
        BankCaseOverrideControler.requestTransactionDetails(caseDetails.Id,baccounts.get(0),'false');
        BankCaseOverrideControler.retriveTransactionDetails(cardBankCaseDetails.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testlogVarification(){
         Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Case_Verification__c cv=new Case_Verification__c();
        cv.Case__c=caseDetails.Id;
        BankCaseOverrideControler.logVarification(cv);
    }
   
   @isTest
    static void requestCreateNewCardTest(){
        Test.setMock(HttpCalloutMock.class, new BankCaseServiceTest.MockCardResponse());
        
        Account a=TestDataFactory.getPersonAccount(true);
        Bank_Account__c ba=TestDataFactory.getBankAccount(a.id,true);
        Case c=TestDataFactory.getBankCase(a.Id,true);
        Bank_Case_Item__c bci=TestDataFactory.getBankAccountBankCase(c.id, false);
        bci.Bank_Account__c=ba.id;
        insert bci;
        
        Test.startTest();
        BankCaseOverrideControler.requestCreateNewCard(bci.id,'{"reference":"123","type":"VISA_DEBIT","line_1":"name on card"}');
        
        Test.stopTest();
     }
    
   
    
}