force-app/main/default/objects/Account/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account IBAN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SyncAccountAndSolarisbankControllerTest.cls
@isTest
public class SyncAccountAndSolarisbankControllerTest {
    
    @isTest
    static void coverTestClass(){
         SyncAccountAndSolarisbankController.coverTestclass();
         SyncAccountAndSolarisbankController.convertCentsToEuro(1000);
    }
    @isTest
    static void teststartSyncWithBank(){
        Account a=TestDataFactory.getPersonAccount(true);
        Test.setMock(HttpCalloutMock.class, new MockResponse(a.Solarisbank_Id__c));
       
        Test.startTest();
       
        SyncAccountAndSolarisbankController.startSyncWithBank(a.Id);
        Test.stopTest();
        SyncAccountAndSolarisbankController.startSyncWithBank(a.Id);
    }

    @isTest
    static void teststartSyncWithBankAccount(){
        Test.setMock(HttpCalloutMock.class, new MockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Bank_Account__c b= TestDataFactory.getBankAccount(a.Id, true);
        Test.startTest();
        SyncAccountAndSolarisbankController.startSyncWithBankAccount(b.Id);
       
        Test.stopTest();
     }
    @isTest
    static void startSyncWithAuthOTest(){
        Test.setMock(HttpCalloutMock.class, new Auth0Wrapper.MockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        Test.startTest();
        SyncAccountAndSolarisbankController.startSyncWithAuthO(a.Id);
        Test.stopTest();
         
    }

    public class MockResponse implements HttpCalloutMock { 
        string sbId='0652225cebcd3bec2c95ea8c461fe146cacc';
        public MockResponse(){}
        public MockResponse(String solarisbankId){
            sbId=solarisbankId;
        }
        public HTTPResponse respond(HTTPRequest req) { 
      
            String endpoint=req.getEndpoint();
            String body='[{"id":"'+sbId+'"}]';
            
            HttpResponse resp = new HttpResponse(); 
            
            resp.setStatusCode(200); 
            
            resp.setStatus('success'); 
            
            if(endpoint.endsWith(sbId)){
                body = '{"last_name":"apiname"}';
            }
            else if(endpoint.endsWith('/mobile_number')){
                body = '{}';
            }
           
            resp.setBody(body); 
            
            return resp; 
            
        }
    }
}