force-app/main/default/objects/Account/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account IBAN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Case__c/Bank_Case__c.object-meta.xml
<CustomObject>
    <label>Bank Case</label>
    <nameField>
        <displayFormat>Bank Case-{00000}</displayFormat>
        <label>Bank Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Case__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Bank Cases</relationshipLabel>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Bank Cases</relationshipLabel>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Bank Cases</relationshipLabel>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Bank Cases</relationshipLabel>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case__c/fields/Scheduled_Order__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Order</label>
    <referenceTo>Scheduled_Order__c</referenceTo>
    <relationshipLabel>Bank Cases</relationshipLabel>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Case__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Bank Cases</relationshipLabel>
    <relationshipName>Bank_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>Booking-{00000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Card Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Type_II__c.field-meta.xml
<CustomField>
    <fullName>Type_II__c</fullName>
    <label>Type II</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Issue</fullName>
            </value>
            <value>
                <fullName>Partner Card Block</fullName>
            </value>
            <value>
                <fullName>Card Chargeback</fullName>
            </value>
            <value>
                <fullName>Card Return/Delivery</fullName>
            </value>
            <value>
                <fullName>Fraudulent Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Card Decline</fullName>
            </value>
            <value>
                <fullName>Partner Card Unblock</fullName>
            </value>
            <value>
                <fullName>Partner Card Closure</fullName>
            </value>
            <value>
                <fullName>Closure Request</fullName>
            </value>
            <value>
                <fullName>Account Statement</fullName>
            </value>
            <value>
                <fullName>Closure Info</fullName>
            </value>
            <value>
                <fullName>Account Confirmation</fullName>
            </value>
            <value>
                <fullName>Tax ID Input</fullName>
            </value>
            <value>
                <fullName>Phone Change (Without access)</fullName>
            </value>
            <value>
                <fullName>Identification Creation</fullName>
            </value>
            <value>
                <fullName>Identification Issues</fullName>
            </value>
            <value>
                <fullName>Identification Complaints</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>User Complaint</fullName>
            </value>
            <value>
                <fullName>Payment Request</fullName>
            </value>
            <value>
                <fullName>Direct Debit Return</fullName>
            </value>
            <value>
                <fullName>Incoming Payment investigation</fullName>
            </value>
            <value>
                <fullName>Payment Recall</fullName>
            </value>
            <value>
                <fullName>Seizure Information Request</fullName>
            </value>
            <value>
                <fullName>Seizures Payout</fullName>
            </value>
            <value>
                <fullName>P-Konto</fullName>
            </value>
            <value>
                <fullName>Information Request</fullName>
            </value>
            <value>
                <fullName>Bank Data Deletion</fullName>
            </value>
            <value>
                <fullName>Bank Data Request</fullName>
            </value>
            <value>
                <fullName>Verification Message Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>Reservation Number-{00000000}</displayFormat>
        <label>Reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Order__c/Scheduled_Order__c.object-meta.xml
<CustomObject>
    <label>Scheduled Order</label>
    <nameField>
        <displayFormat>SO-{0000000}</displayFormat>
        <label>Scheduled Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Order__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipName>Scheduled_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Order__c/fields/Solarisbank_Id__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Id__c</fullName>
    <externalId>true</externalId>
    <label>Solarisbank Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <label>Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Statement__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BankCaseServiceTest.cls
@isTest
public class BankCaseServiceTest {
    @isTest
    static void testchangeCardStatusToJira(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCardWrapper.MockResponse());
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case__c cardBankCaseDetails=TestDataFactory.getCardBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Card__c=cardDetails.Id;
        insert cardBankCaseDetails;
        Bank_Case__c bcase=BankCaseOverrideControler.getBankCaseDetails(cardBankCaseDetails.Id);
        Test.startTest();
        
        BankCaseOverrideControler.changeCardStatus(bcase,'Block','Test It',true);
        Test.stopTest();
    }
    @isTest
    static void testchangeCardStatusBlock(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCardWrapper.MockResponse());
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case__c cardBankCaseDetails=TestDataFactory.getCardBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Card__c=cardDetails.Id;
        insert cardBankCaseDetails;
        Bank_Case__c bcase=BankCaseOverrideControler.getBankCaseDetails(cardBankCaseDetails.Id);
        Test.startTest();
        
        BankCaseOverrideControler.changeCardStatus(bcase,'Block','Test It',false);
        Test.stopTest();
    }
    @isTest
    static void testchangeCardStatusClose(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCardWrapper.MockResponse());
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case__c cardBankCaseDetails=TestDataFactory.getCardBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Card__c=cardDetails.Id;
        insert cardBankCaseDetails;
        Bank_Case__c bcase=BankCaseOverrideControler.getBankCaseDetails(cardBankCaseDetails.Id);
        Test.startTest();
        try{
            BankCaseOverrideControler.changeCardStatus(bcase,'Unblock','Test It',false);
            BankCaseOverrideControler.changeCardStatus(bcase,'Close','Test It',false);
        }catch(exception e){}
        Test.stopTest();
    }
    @isTest 
    static void initiateTimedOrderCancelationNegative(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankCardWrapper.MockResponse());
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case__c cardBankCaseDetails=TestDataFactory.getTimedOrderBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Scheduled_Order__c=tOrder.Id;
        insert cardBankCaseDetails;
        Bank_Case__c bcase=BankCaseOverrideControler.getBankCaseDetails(cardBankCaseDetails.Id);
        Test.startTest();
        try{
        BankCaseOverrideControler.requestCancleTimedOrder(bcase,'Test It');
        }catch(exception e){}
        Test.stopTest();
    }
    @isTest 
    static void initiateTimedOrderCancelation(){
        Test.setMock(HttpCalloutMock.class, new SolarisbankTimedOrderWrapper.MockResponse());
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Bank_Case__c cardBankCaseDetails=TestDataFactory.getTimedOrderBankCase(caseDetails.Id,false);
        cardBankCaseDetails.Scheduled_Order__c=tOrder.Id;
        insert cardBankCaseDetails;
        Bank_Case__c bcase=BankCaseOverrideControler.getBankCaseDetails(cardBankCaseDetails.Id);
        Test.startTest();
        BankCaseOverrideControler.requestCancleTimedOrder(bcase,'Test It');
        
        Test.stopTest();
    }
    
    @isTest
    static void testcreateBankCasesRecords(){
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Statement__c state=New Statement__c();
        state.Bank_Account__c=bankAccountDetails.id;
        state.Solarisbank_Id__c='0652225cebcd3bec2c95ea8c461fe146cacc';
        insert state;
        Test.startTest();
        BankCaseOverrideControler.createBankCases(caseDetails.Id,caseDetails.Type,caseDetails.Type_II__c,caseDetails.Description, 
                                                  bankAccountDetails.Id,cardDetails.Id,accountDetails.Id,
                                                  new List<String>{booking.Id},new List<String>{res.Id},
                                                  new List<String>{tOrder.Id},new List<String>{sOrder.Id},state.id);
         BankCaseOverrideControler.createBankCases(caseDetails.Id,caseDetails.Type,caseDetails.Type_II__c,caseDetails.Description, 
                                                  bankAccountDetails.Id,cardDetails.Id,accountDetails.Id,
                                                  new List<String>{booking.Id},new List<String>{res.Id},
                                                  new List<String>{tOrder.Id},new List<String>{sOrder.Id},state.Id);
        Test.stopTest();
    }
    @isTest
    static void testcreateBankCasesRecordsNegetive(){
        Account accountDetails=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bankAccountDetails = TestDataFactory.getBankAccount(accountDetails.Id,true);
        Card__c cardDetails=TestDataFactory.getCard(accountDetails.Id,bankAccountDetails.Id,true);
        Booking__c booking=TestDataFactory.getBooking(bankAccountDetails.Id,true);
        Scheduled_Order__c tOrder=TestDataFactory.getTimedOrder(bankAccountDetails.Id,true);
        Scheduled_Order__c sOrder=TestDataFactory.getStandingOrder(bankAccountDetails.Id,true);
        Reservation__c res=TestDataFactory.getReservation(bankAccountDetails.Id,true);
        
        Case caseDetails=TestDataFactory.getBankCase(accountDetails.Id,true);
        Test.startTest();
        try{
        BankCaseOverrideControler.createBankCases(caseDetails.Id,caseDetails.Type,caseDetails.Type_II__c,caseDetails.Description, 
                                                  bankAccountDetails.Id,cardDetails.Id,accountDetails.Id,
                                                 
                                                  new List<String>{tOrder.Id}, new List<String>{booking.Id},new List<String>{res.Id},
                                                  new List<String>{sOrder.Id},'');
        }catch(Exception e){}
        Test.stopTest();
    }
}