force-app/main/default/objects/Account/fields/Solarisbank_Tenent__c.field-meta.xml
<CustomField>
    <fullName>Solarisbank_Tenent__c</fullName>
    <label>Solarisbank Tenent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Investment_Status__c.field-meta.xml
<CustomField>
    <fullName>Investment_Status__c</fullName>
    <formula>IF( CASESAFEID(RecordTypeId) == $CustomMetadata.Constant__mdt.OpportuntiyInvestmentRecordTypeId.Value__c  , 
IF(ISPICKVAL( StageName , &quot;ACTIVE&quot;), &quot;ACTIVE&quot;,  
IF(ISPICKVAL( StageName , &quot;Closed Won&quot;), &quot;CLOSED_WON&quot;, 
IF(ISPICKVAL( StageName , &quot;Closed Lost&quot;), &quot;CLOSED_LOST&quot;,
 &quot;WAIT_FOR_START_DATE&quot;)))
,&quot;&quot;)</formula>
    <label>Investment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Money_Transferred__c.field-meta.xml
<CustomField>
    <fullName>Is_Money_Transferred__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Money Transferred</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Money_Transfer_Confirmed_By__c.field-meta.xml
<CustomField>
    <fullName>Money_Transfer_Confirmed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Money Transfer Confirmed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SMI_OpportuntiyInvestmentService.cls
public class SMI_OpportuntiyInvestmentService {
    
    @AuraEnabled
    public static void sendMoneyTransferConformation(String oppId){
        try{         
            Opportunity oppDetails=[SELECT Id,External_Id__c ,Account.Solarisbank_Tenent__c,Is_Money_Transferred__c, Money_Transfer_Confirmed_By__c FROM Opportunity WHERE id=:oppId];
            if(!oppDetails.Is_Money_Transferred__c){
                LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(oppDetails.Id,'Opportunity',oppDetails.Account.Solarisbank_Tenent__c);
                String statusResponse=EVExternalService.sendInvestmentMoneyTransferdStatus(oppDetails.External_Id__c,true,apiCallDetails);
                oppDetails.Is_Money_Transferred__c=true;
                oppDetails.Money_Transfer_Confirmed_By__c=Userinfo.getUserId();
                update oppDetails;
            }
        }
        catch(Exception e){
            String index = logError(e,oppId,'Opportunity','SMI_OpportuntiyInvestmentConformMoneyTransfer','sendMoneyTransferConformation','SMI Money Transfer Conformation');
            throw new AuraHandledException('Please contact your System admin.And provide '+index+' id to resolve issue.');
        }
    }
    
    @InvocableMethod(label='Send Investment Status to EV')
    public static void sendStatusToEV(List<String> oppIds) {

        List<Opportunity> oppDetails=[SELECT Id,Investment_Status__c ,External_Id__c ,Account.Solarisbank_Tenent__c,Is_Money_Transferred__c, Money_Transfer_Confirmed_By__c FROM Opportunity WHERE id IN:oppIds];
        for(Opportunity opp:oppDetails){
            try{ 
                LogService.ApiCallDetails apiCallDetails =  new LogService.ApiCallDetails(opp.Id,'Opportunity',opp.Account.Solarisbank_Tenent__c);
                EVExternalService.sendInvestmentStatusChange(opp.External_Id__c,opp.Investment_Status__c,apiCallDetails);
                
            }
            catch(Exception e){
                String index = logError(e,oppDetails.get(0).Id,'Opportunity','SMI_OpportuntiyInvestmentConformMoneyTransfer','sendStatusToEV','SMI Invesment Status Change');
                throw new EVException('Please contact your System admin.And provide '+index+' id to resolve issue.');
            }
        }
    }
    
    //helper
    private static String logError(Exception e,String recordID,String objectName,String componentName,String methodName,String operation){
        LogService.LogMetadata details=new LogService.LogMetadata();
        details.addError(e);
        details.addRecordInfo(objectName,recordId);
        
        details.addMetadataInfo(userinfo.getUserId(),'SMI_OpportuntiyInvestmentService', methodName, componentName, operation);
        return LogService.logError(details);
    }
}