force-app/main/default/objects/Account/fields/Terms_Conditions_Signed_At__c.field-meta.xml
<CustomField>
    <fullName>Terms_Conditions_Signed_At__c</fullName>
    <label>Bank Terms Conditions Signed At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Scramble_Configuration__c/Scramble_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuration of field and object to scramble PII data</description>
    <label>Scramble Configuration</label>
</CustomObject>

force-app/main/default/objects/Scramble_Configuration__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <inlineHelpText>Api Name of Field</inlineHelpText>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scramble_Configuration__c/fields/IsReference__c.field-meta.xml
<CustomField>
    <fullName>IsReference__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Lookup Field to account on object</inlineHelpText>
    <label>IsReference</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scramble_Configuration__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>API Name of object</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountScrambleDataTest.cls
/***************
* @group Test Class
* @description test class for AccountScrambleData
*/
@isTest
public class AccountScrambleDataTest {

    @testSetup
    static void setup(){
        List<Scramble_Configuration__c> scrableFields=new List<Scramble_Configuration__c>();
        scrableFields.add(new Scramble_Configuration__c(Field__c='Id',Object__c='Account',Name='Id',IsReference__c=true));
        scrableFields.add(new Scramble_Configuration__c(Field__c='LastName',Object__c='Account',Name='Name',IsReference__c=false));
        scrableFields.add(new Scramble_Configuration__c(Field__c='PersonBirthdate',Object__c='Account',Name='PersonBirthdate',IsReference__c=false));
        scrableFields.add(new Scramble_Configuration__c(Field__c='Age__pc',Object__c='Account',Name='Age',IsReference__c=false));
        scrableFields.add(new Scramble_Configuration__c(Field__c='Terms_Conditions_Signed_At__c',Object__c='Account',Name='Terms_Conditions_Signed',IsReference__c=false));
        scrableFields.add(new Scramble_Configuration__c(Field__c='PersonEmail',Object__c='Account',Name='PersonEmail',IsReference__c=false));
        
        scrableFields.add(new Scramble_Configuration__c(Field__c='AccountId',Object__c='Opportunity',Name='Opp_Id',IsReference__c=true));
        scrableFields.add(new Scramble_Configuration__c(Field__c='Amount',Object__c='Opportunity',Name='Amount',IsReference__c=false));
        scrableFields.add(new Scramble_Configuration__c(Field__c='StageName',Object__c='Opportunity',Name='StageName',IsReference__c=false));
        scrableFields.add(new Scramble_Configuration__c(Field__c='CloseDate',Object__c='Opportunity',Name='CloseDate',IsReference__c=false));
        
        insert scrableFields;
        
        Account personAccount=TestDataFactory.getPersonAccount(false);
        Date d=Date.today();
        personAccount.PersonBirthdate=d.addYears(-100); 
        personAccount.Age__pc='01-10';
        personAccount.Terms_Conditions_Signed_At__c=DateTime.now();
        personAccount.PersonEmail='asdfg@asdf.com';
        insert personAccount;
     
        Opportunity opp=TestDataFactory.getOpportunityFullSale(personAccount.id,false);
        opp.Amount=100;
        opp.StageName='Qualification';
        opp.CloseDate=Date.today()+3;
        insert opp;
    }
    
    @isTest
    static void scrambleDataSucess(){
        Account a=[SELECT id FROM Account];
        Test.startTest();
        
        System.enqueueJob(new AccountScrambleData(new List<String>{a.Id}));
        Test.stopTest();
    }
    @isTest
    static void logRecordErrorTest(){
        Account personAccount=TestDataFactory.getPersonAccount(false);
        Date d=Date.today();
        personAccount.PersonBirthdate=d.addYears(-100); 
        
        personAccount.Terms_Conditions_Signed_At__c=DateTime.now();
        personAccount.PersonEmail='asdfg@asdf.com';
        insert personAccount;
        update personAccount;
        Test.startTest();
        AccountScrambleData scrable=new AccountScrambleData(new List<String>{});
        scrable.logError('','',null);
        Test.stopTest();
            
            
    }
    
}