force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Subscription-{00000}</displayFormat>
        <label>Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Subscription_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Subscription_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Subscribed</fullName>
        <default>true</default>
        <label>Not Subscribed</label>
    </customValue>
    <customValue>
        <fullName>Awaiting Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Subscribed</fullName>
    </customValue>
    <customValue>
        <fullName>Unsubscribed</fullName>
    </customValue>
    <customValue>
        <fullName>Resend Confirmation</fullName>
    </customValue>
    <masterLabel>Product Subscription Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SubscriptionServiceTest.cls
@isTest
private class SubscriptionServiceTest {
    
    @isTest
    static void testSubscription(){
        Account a=TestDataFactory.getPersonAccount(true);
        Subscription__c sub=TestDataFactory.getNewsletterSubscription(a.Id,[SELECT id FROM Contact LIMIT 1].Id ,true);
        Test.startTest();
        Boolean b=SubscriptionService.checkAndUpdateSubscriptionOnload(a.PersonEmail,'Newsletter').showForm;
        SubscriptionService.updateSubscriptionWithConfirmation(a.PersonEmail, 'Newsletter', '', '','',true, '', a.Id);
        System.assert(b);
        Test.stopTest();
    }
     @isTest
    static void testUnSubscription(){
        Account a=TestDataFactory.getPersonAccount(true);
        Subscription__c sub=TestDataFactory.getNewsletterSubscription(a.Id,[SELECT id FROM Contact LIMIT 1].Id ,false);
        sub.Subscription_Status__c='Unsubscribed'; 
        insert sub;
        Test.startTest();
        SubscriptionService.checkUnsubscribedStatus(a.PersonEmail,'Newsletter');
        SubscriptionService.updateSubscriptionToUnSubscribed(a.PersonEmail,'Newsletter','');
        SubscriptionService.getUnsubscribeOptions();
        SubscriptionService.getLastEmailSentInfo(sub.Id);
        Test.stopTest();
    
    }

}