force-app/main/default/objects/Knowledge__kav/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Information__c.field-meta.xml
<CustomField>
    <fullName>Information__c</fullName>
    <label>Information</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tech</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Master Data Management</fullName>
            </value>
            <value>
                <fullName>Identification</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Card Management</fullName>
            </value>
            <value>
                <fullName>Complaints</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>AML</fullName>
            </value>
            <value>
                <fullName>Seizures</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anti-Fraud Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Type_II__c.field-meta.xml
<CustomField>
    <fullName>Type_II__c</fullName>
    <label>Type II</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Issue</fullName>
            </value>
            <value>
                <fullName>Partner Card Block</fullName>
            </value>
            <value>
                <fullName>Card Chargeback</fullName>
            </value>
            <value>
                <fullName>Card Return/Delivery</fullName>
            </value>
            <value>
                <fullName>Fraudulent Transaction Monitoring</fullName>
            </value>
            <value>
                <fullName>Card Decline</fullName>
            </value>
            <value>
                <fullName>Partner Card Unblock</fullName>
            </value>
            <value>
                <fullName>Partner Card Closure</fullName>
            </value>
            <value>
                <fullName>Closure Request</fullName>
            </value>
            <value>
                <fullName>Account Statement</fullName>
            </value>
            <value>
                <fullName>Account Confirmation</fullName>
            </value>
            <value>
                <fullName>Tax ID Input</fullName>
            </value>
            <value>
                <fullName>Phone Change (Without access)</fullName>
            </value>
            <value>
                <fullName>Identification Creation</fullName>
            </value>
            <value>
                <fullName>Identification Issues</fullName>
            </value>
            <value>
                <fullName>Identification Complaints</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>User Complaint</fullName>
            </value>
            <value>
                <fullName>Payment Request</fullName>
            </value>
            <value>
                <fullName>Direct Debit Return</fullName>
            </value>
            <value>
                <fullName>Incoming Payment investigation</fullName>
            </value>
            <value>
                <fullName>Payment Recall</fullName>
            </value>
            <value>
                <fullName>Seizure Information Request</fullName>
            </value>
            <value>
                <fullName>Seizures Payout</fullName>
            </value>
            <value>
                <fullName>P-Konto</fullName>
            </value>
            <value>
                <fullName>Information Request</fullName>
            </value>
            <value>
                <fullName>Bank Data Deletion</fullName>
            </value>
            <value>
                <fullName>Bank Data Request</fullName>
            </value>
            <value>
                <fullName>Verification Message Issue</fullName>
            </value>
            <value>
                <fullName>General Tech Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KnowledgeTriggerHandler.cls
/***************
* @group Handler Class
* @description Knowledge Trigger router
*/
public class KnowledgeTriggerHandler extends TriggerHandler {
    protected override void beforeInsert() {
        List<Knowledge__kav> newRecords=Trigger.new;
        Map<String,Knowledge__kav> newDraftLocalArticles=new Map<String,Knowledge__kav>();
        
        
        for(Knowledge__kav record:newRecords){
            
            //auto poupulate url name if not defined
            if(record.UrlName==null || String.isEmpty(record.UrlName)) {
                if(record.Title!=null || !(String.isEmpty(record.Title))) {
                    record.UrlName = record.Title.toLowerCase().replaceAll('[^a-z0-9\\s]','-').replaceAll(' ','-').replaceAll('-+','-').replaceFirst('-','').removeEnd('-').replaceFirst('_','').removeEnd('_').removeEnd('-').abbreviate(255).trim(); 
                }
            } 
            
             //checking if local is created
            if(record.PublishStatus =='Draft' && record.IsMasterLanguage==false){
                newDraftLocalArticles.put(record.KnowledgeArticleId,record);
            }    
        }
        
        //copy english data to local
        if(newDraftLocalArticles.size()>0) copyMasterDataToLocal(newDraftLocalArticles);
        
    }
    
    private static String fieldsToCopy='Summary,Information__c,Question__c,Type__c,Type_II__c,Category__c';
    
    //get master language data
    private static Map<String,Knowledge__kav> getMasterLanguageData(Map<String,Knowledge__kav> draftLocalArticles){
        Map<String,Knowledge__kav> englishArticleMap=new Map<String,Knowledge__kav>();
        
        Set<String> kmArticleIds=draftLocalArticles.keySet();
        //get draft version 
        List<Knowledge__kav> englishDraftArticles=Database.query('SELECT Id,KnowledgeArticleId,'+fieldsToCopy+' FROM Knowledge__kav WHERE KnowledgeArticleId=:kmArticleIds AND PublishStatus =\'Draft\' AND IsMasterLanguage=true ');
        for(Knowledge__kav draftOnline:englishDraftArticles) englishArticleMap.put(draftOnline.KnowledgeArticleId,draftOnline);
        //get english version
        List<Knowledge__kav> englishOnlineArticles=Database.query('SELECT Id,KnowledgeArticleId,'+fieldsToCopy+' FROM Knowledge__kav WHERE KnowledgeArticleId=:kmArticleIds AND PublishStatus =\'Online\' AND IsMasterLanguage=true ');
        for(Knowledge__kav englishOnline:englishOnlineArticles) englishArticleMap.put(englishOnline.KnowledgeArticleId,englishOnline);
       
        return englishArticleMap;
        
    }
    
    //copy data from master langauage to locals
    private static void copyMasterDataToLocal(Map<String,Knowledge__kav> draftLocalArticles){
        Map<String,Knowledge__kav> englishArticleData=getMasterLanguageData(draftLocalArticles);
        for(String kmId:draftLocalArticles.keySet()){
            if(englishArticleData.containsKey(kmId)){
                Knowledge__kav localRecord=draftLocalArticles.get(kmId);
                Knowledge__kav masterRecord=englishArticleData.get(kmId);
                for(String field:fieldsToCopy.split(',')){
                    localRecord.put(field.trim(),masterRecord.get(field.trim()));
                }
            }
        }
    }

}