force-app/main/default/objects/Knowledge__kav/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tech</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Master Data Management</fullName>
            </value>
            <value>
                <fullName>Identification</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Card Management</fullName>
            </value>
            <value>
                <fullName>Complaints</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>AML</fullName>
            </value>
            <value>
                <fullName>Seizures</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Anti-Fraud Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestServiceTranslationTest.cls
/***************
* @group Test Class
* @description test class for RestServiceTranslation 
*/
@isTest
public class RestServiceTranslationTest {
    @isTest
    static void doGetSuccess(){
        
        
        Test.startTest();
        String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        req.requestURI = baseUrl+'/services/apexrest/Translation/PickList/Knowledge__kav/Type__c'; 
        req.httpMethod = 'GET';
        req.addHeader('Content-Type', 'application/json');
        
        RestContext.request = req;
        RestServiceTranslation.doGet();    
        System.assertEquals(200,res.statusCode);
        Test.stopTest();   
    }
    @isTest
    static void doGetInvlaidMetadata(){
        
        
        Test.startTest();
        String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        req.requestURI = baseUrl+'/services/apexrest/Translation/Label/Knowledge__kav/Type__c'; 
        req.httpMethod = 'GET';
        req.addHeader('Content-Type', 'application/json');
        
        RestContext.request = req;
        RestServiceTranslation.doGet();    
        System.assertEquals(400,res.statusCode);
        Test.stopTest();   
    }
    @isTest
    static void doGetInvlaidObject(){
        
        
        Test.startTest();
        String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        req.requestURI = baseUrl+'/services/apexrest/Translation/PickList/Knowledge/Type__c'; 
        req.httpMethod = 'GET';
        req.addHeader('Content-Type', 'application/json');
        
        RestContext.request = req;
        RestServiceTranslation.doGet();    
        System.assertEquals(400,res.statusCode);
        Test.stopTest();   
    }
     @isTest
    static void doGetInvalidField(){
        
        
        Test.startTest();
        String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        req.requestURI = baseUrl+'/services/apexrest/Translation/PickList/Knowledge__kav/Name__c'; 
        req.httpMethod = 'GET';
        req.addHeader('Content-Type', 'application/json');
        
        RestContext.request = req;
        RestServiceTranslation.doGet();    
        System.assertEquals(400,res.statusCode);
        Test.stopTest();   
    }
    
@isTest
    static void logErrorTest(){
        Test.startTest();
        try{
            Integer i=1/0;
        }
        Catch(Exception e){
            RestServiceTranslation.logError(e,'Test');
        }
        Test.stopTest();
    }
}