force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account IBAN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/JIRA_Description__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Description__c</fullName>
    <label>JIRA Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/KYC_Detail__c/KYC_Detail__c.object-meta.xml
<CustomObject>
    <label>KYC Detail</label>
    <nameField>
        <displayFormat>KYC-{00000}</displayFormat>
        <label>KYC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYC Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BankingServiceTest.cls
@isTest
public class BankingServiceTest {

    
    @isTest
    static void testStaticValues(){
        BankingService.checkIsCompactLayout();
        BankingService.getBankCaseTypes();
        BankingService.getCaseIITypes();
        BankingService.retriveDefaultTemplatHtml();
    }
    @isTest
    static void testupdateJiraInformationNegative(){
        Account a=TestDataFactory.getPersonAccount(true);
        Case c=TestDataFactory.getBankCase(a.id,true);
        try{
            Test.startTest();
            BankingService.updateJiraInformation('c.Id','String subject','String discription',new List<String>{});
            
            Test.stopTest();
        }catch(Exception e){}
    }
    @isTest
    static void testupdateJiraInformation(){
        Account a=TestDataFactory.getPersonAccount(true);
        Case c=TestDataFactory.getBankCase(a.id,true);
        BankingService.retriveCaseDetails(a.Id);
        BankingService.retriveProcessKnowlodge('MDM','ACS');
         
		Test.startTest();
        BankingService.updateJiraInformation(c.Id,'String subject','String discription',new List<String>{});
        BankingService.retriveContentVersionList(c.Id);
        Case cc=[SELECT JIRA_Description__c  FROM CASE LIMIT 1];
        System.assert(cc.JIRA_Description__c !=null);
 		Test.stopTest();
    }
    @isTest
    static void testretriveBankBalanceDetails(){
        Test.setMock(HttpCalloutMock.class, new SolarisBankTaxIdentificationWrapper.MockResponse());

        Account a=TestDataFactory.getPersonAccount(true);
        Bank_Account__c bc=TestDataFactory.getBankAccount(a.id,true);
        Test.startTest();
        
        BankingService.retriveBankBalanceDetails(bc.Id);
        Test.stopTest();
    }
  
    @isTest
    static void testretriveIdentificationDetailsAndUpdate(){
        Test.setMock(HttpCalloutMock.class, new SolarisBankIdentificationWrapper.MockResponse());
        Account a=TestDataFactory.getPersonAccount(true);
        KYC_Detail__c ident=TestDataFactory.getKYCVideoIdentification(a.Id,true);
        Test.startTest();
        BankingService.retriveIdentificationDetailsAndUpdate(ident.id);
        Test.stopTest();

    }
 
}