force-app/main/default/objects/Email_Configuration__c/Email_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Control emails that are sent costumers</description>
    <label>Email Configuration</label>
</CustomObject>

force-app/main/default/objects/Email_Configuration__c/fields/Send_Subscribed_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Subscribed_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Subscribed Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MailUtilityTest.cls
@isTest
private class MailUtilityTest {

    @isTest
    static void sendMailsTest(){
        Email_Configuration__c config = new Email_Configuration__c();
        config.Send_Subscribed_Email__c=true;
        insert config;
        Lead l=TestDataFactory.getWebLead(true);
        Account a=TestDataFactory.getPersonAccount(true);
        MailUtility.sendLeadHtmlEmail(l.Id, Constant.LEAD_SUBSCRIBED_EMAIL_TEMPLATE, l.Email);
        Contact c=[Select id FROM Contact];
        MailUtility.sendAccountHtmlEmail(c.id,a.id, Constant.ACCOUNT_SUBSCRIBED_EMAIL_TEMPLATE,a.PersonEmail);
    }
}