force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account IBAN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <label>Campaign</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/TestDataFactoryTest.cls
/***************
* @group Test Class
* @description test class for TestDataFactory
*/
@isTest
public class TestDataFactoryTest {
    
    
    @isTest
    public static void getStandaloneGenerators(){
        Account bizAccount=TestDataFactory.getBusinessAccount(true);
        Account personAccount=TestDataFactory.getPersonInvestmentAccount(true);
        Bank_Account__c bankAccount=TestDataFactory.getBankAccount(personAccount.Id, true);
        Lead lead=TestDataFactory.getWebLead(true);
        Campaign camp=TestDataFactory.getStandardCampaign(true);
        Contact con=TestDataFactory.getContact(true);
        
        TestDataFactory.getChangeRequestLog(bizAccount.id,true);
        TestDataFactory.getContactCampaignMember(camp.id, con.id,true);        
        TestDataFactory.getLeadCampaignMember(camp.id, lead.id, true);
        TestDataFactory.getCard(personAccount.id, bankAccount.id, true);
        TestDataFactory.getReservation(bankAccount.id,true);
        TestDataFactory.getUser('Integration');
        TestDataFactory.getSeziure(personAccount.id,true);
        TestDataFactory.getContentVersion(true);
        TestDataFactory.getDocumentForAccount(personAccount.id,true);
        
    }

    @isTest
    public static void getBankGeneratorsTest(){
        Account personAccount=TestDataFactory.getPersonAccount(true);
        Bank__c bank=TestDataFactory.getBankSolarisBank(personAccount.id,true);
        Bank_Account__c bankAccount=TestDataFactory.getBankAccount(personAccount.Id, true);
        TestDataFactory.getKYCVideoIdentification(personAccount.Id,true);
        TestDataFactory.getBooking(bankAccount.id,true);
        TestDataFactory.getTimedOrder(bankAccount.id,true);
        TestDataFactory.getStandingOrder(bankAccount.id,true);
        
        
    }
    @isTest
    public static void getOpportuntiyGeneratorsTest(){
        Account personAccount=TestDataFactory.getPersonAccount(true);
        
        TestDataFactory.getStandardOpportunity(personAccount.id,true);
        TestDataFactory.getOpportunityFullSale(personAccount.id,true);
        TestDataFactory.getBankCase(personAccount.id, true);
        
    }
    @isTest
    public static void getCaseGeneratorsTest(){
        Account personAccount=TestDataFactory.getPersonAccount(true);
        
        TestDataFactory.getStandardCase(personAccount.id,true);
        TestDataFactory.getBankCase(personAccount.id, true);
        TestDataFactory.getEVKontoCase(personAccount.id, true);
        TestDataFactory.getCaseInvestment(personAccount.id, true);
        
    }
    
    @isTest
    public static void getBankCaseItemGeneratorsTest(){
        Account personAccount=TestDataFactory.getPersonAccount(true);
        Case c=   TestDataFactory.getBankCase(personAccount.id, true);
        TestDataFactory.getAccountBankCase( c.id,true);
        TestDataFactory.getCardBankCase( c.id,true);
        TestDataFactory.getBookingBankCase( c.id,true);
        TestDataFactory.getBankAccountBankCase( c.id,true);
        TestDataFactory.getTimedOrderBankCase( c.id,true);
    }
    @isTest
    public static void getAssetGeneratorsTest(){
        Account personAccount=TestDataFactory.getPersonAccount(true);
        Contact c=[SELECT id FROM Contact WHERE accountId=:personAccount.Id];
        Asset asset=TestDataFactory.getAssetRealEstate(personAccount.id, c.Id,true);
        TestDataFactory.getAssetLink(asset.id,true);
        TestDataFactory.getAssetEvaluation(asset.id, true);
        
    }
    
    @isTest
    static void getLogGeneratorsTest(){
        Account personAccount=TestDataFactory.getPersonAccount(true);
        TestDataFactory.getDebugLog(personAccount.id,true);
        TestDataFactory.getDebugLog(personAccount.id,true);
        TestDataFactory.getChangeHistoryLog(personAccount.id,true);
        TestDataFactory.getViewHistoryLog(personAccount.id,true);
        
        
    }
}